conf/cmi/core.entity_form_display.node.imported_article.default.yml
conf/cmi/core.entity_view_display.node.imported_article.default.yml
conf/cmi/core.entity_view_display.node.imported_article.teaser.yml
conf/cmi/core.extension.yml
conf/cmi/field.field.node.imported_article.body.yml
conf/cmi/field.field.node.imported_article.field_image.yml
conf/cmi/field.storage.node.field_image.yml
conf/cmi/language.content_settings.node.imported_article.yml
conf/cmi/node.type.imported_article.yml
conf/cmi/views.view.imported_articles.yml
public/modules/custom/paatokset_news_importer/config/install/core.entity_form_display.node.imported_article.default.yml
public/modules/custom/paatokset_news_importer/config/install/core.entity_view_display.node.imported_article.default.yml
public/modules/custom/paatokset_news_importer/config/install/core.entity_view_display.node.imported_article.teaser.yml
public/modules/custom/paatokset_news_importer/config/install/field.field.node.imported_article.body.yml
public/modules/custom/paatokset_news_importer/config/install/field.field.node.imported_article.field_image.yml
public/modules/custom/paatokset_news_importer/config/install/field.storage.node.field_image.yml
public/modules/custom/paatokset_news_importer/config/install/language.content_settings.node.imported_article.yml
public/modules/custom/paatokset_news_importer/config/install/node.type.imported_article.yml
public/modules/custom/paatokset_news_importer/config/optional/views.view.imported_articles.yml
public/modules/custom/paatokset_news_importer/migrations/paatokset_news.yml
public/modules/custom/paatokset_news_importer/migrations/paatokset_news_images.yml
public/modules/custom/paatokset_news_importer/paatokset_news_importer.info.yml
public/modules/custom/paatokset_news_importer/paatokset_news_importer.module
public/modules/custom/paatokset_news_importer/src/Plugin/migrate/source/ImportedArticle.php
public/modules/custom/paatokset_news_importer/templates/node--imported-article.html.twig
public/modules/custom/paatokset_news_importer/templates/page--imported-article.html.twig
public/modules/custom/paatokset_news_importer/templates/views-view-unformatted--imported-articles.html.twig
public/modules/custom/paatokset_news_importer/tests/src/Kernel/ImportedArticleMigrationTest.php
public/modules/custom/paatokset_news_importer/tests/src/Kernel/Plugin/migrate/source/ImportedArticleTest.php
public/modules/custom/paatokset_news_importer/tests/src/Traits/ImportedArticleTestTrait.php

Add news feed integration module, changes:
- New custom module paatokset_news_importer
- Added new node type imported_article
- Custom module contains migrations
- Module contains view for imported_articles feed, will be styled later
- Contains template for imported articles, which is basically a copy+paste of article template
To test:
- `make drush-cr; make drush-cim`
- paatokset_news_importer should ne installed now
- run new custom migrations: `PARTIAL_MIGRATE=1 drush migrate:import paatokset_news_images; PARTIAL_MIGRATE=1 drush migrate:import paatokset_news` - env variable set here prevents helfi_api_base event subscriber from failing the migration, but does not affect this one
- Content of type imported_article should be imported from the RSS feed

PP-76: News feed integration module

---

composer.lock
conf/cmi/core.extension.yml
conf/cmi/select2_icon.settings.yml

Core 9.1.7 -> 9.1.8
Helfi_* modules haven been updated. Install location has been moved from custom to contrib directory. 
To test:
- `make build; make post-install; drush-cr;`
- Most helfi -prefixed modules should have moved from `public/modules/custom` to `public/modules/contrib`
- Verify that site still works

Updated core + all modules + changed helfi_* module settings

---

conf/cmi/core.entity_form_display.node.policymaker.default.yml
conf/cmi/core.entity_view_display.node.policymaker.default.yml
conf/cmi/field.field.node.policymaker.field_first_name.yml
conf/cmi/field.field.node.policymaker.field_last_name.yml
conf/cmi/field.storage.node.field_first_name.yml
conf/cmi/field.storage.node.field_last_name.yml

Added first/last name fields to policymaker node type.
To test:
- Run `make drush-cim`
- Check `https://helsinki-paatokset.docker.so/fi/admin/structure/types/manage/policymaker/fields` to see fields.

PP-197: Added first/last name fields to policymakers

---

conf/cmi/views.view.declarations_of_affiliation.yml

Added a view for declarations of affiliation
To test:
- Run `drush-cim`
- Add some taxonomy terms here: https://helsinki-paatokset.docker.so/fi/admin/structure/taxonomy/manage/pdf_categories/overview
- Add or modify some `declaration_of_affiliation` media entities to reference these terms through `Interest statement category` field
- Visit `https://helsinki-paatokset.docker.so/fi/declarations-of-affiliation`. It should look like:

PP-152: Add view for declarations of affiliation

---

.gitignore
docker-compose.yml
public/modules/custom/paatokset_ahjo_openid/paatokset_ahjo_openid.info.yml
public/modules/custom/paatokset_ahjo_openid/paatokset_ahjo_openid.links.menu.yml
public/modules/custom/paatokset_ahjo_openid/paatokset_ahjo_openid.routing.yml
public/modules/custom/paatokset_ahjo_openid/paatokset_ahjo_openid.services.yml
public/modules/custom/paatokset_ahjo_openid/src/AhjoOpenId.php
public/modules/custom/paatokset_ahjo_openid/src/Controller/AhjoOpenIdController.php
public/modules/custom/paatokset_ahjo_openid/src/Form/SettingsForm.php

This requires VPN and IT account access, so testing will be limited to some surface areas and checking that the code makes sense.
**To test:**
* Create a new file in the project root: `.env.local`
* Add this content in the file: `PAATOKSET_OPENID_SECRET=insert_client_secret_here` (not the real secret, but this can't be tested anyway without VPN access)
* Run `make up`
* Run `make shell`
* Inside the container, run `printenv`. Make sure the content you added in the env.local file is there 
* Inside the container, run `drush en paatokset_ahjo_openid`
* Check that the status page works:  https://helsinki-paatokset.docker.so/fi/admin/ahjo-open-id
* Check that the config page works: https://helsinki-paatokset.docker.so/fi/admin/ahjo-open-id/settings
* Read code changes. Is …

PP-191: OpenID connect authentication flow.

---

public/modules/custom/paatokset_ahjo/migrations/paatokset_agenda_items.yml
public/modules/custom/paatokset_ahjo/migrations/paatokset_attachments.yml
public/modules/custom/paatokset_ahjo/migrations/paatokset_issues.yml
public/modules/custom/paatokset_ahjo/migrations/paatokset_meeting_documents.yml
public/modules/custom/paatokset_ahjo/migrations/paatokset_meetings.yml
public/modules/custom/paatokset_ahjo/migrations/paatokset_organizations.yml
public/modules/custom/paatokset_ahjo/src/Plugin/migrate/source/PaatoksetOpenAhjo.php

**To test**
* Run `make shell`
* Run `drush cr;drush mim paatokset_agenda_items;drush mim paatokset_attachments;drush mim paatokset_issues;drush mim paatokset_meeting_documents;drush mim paatokset_meetings`
* Each migration should only import about 1000 to 2000 pieces of content and the whole thing shouldn't take an impossible amount of time
* Each endpoint should be sorted by the last updated time, except for paatokset_attachments, which uses an offset to skip to the last few thousand entires
* The policymaker and organization migrations are not limited because they have a reasonable amount of content
* Test that the issue and agenda item pages have enough content so the frontend functionality can be tested

PP-211: Add limits to amount of content imported from old API

---

composer.json
composer.lock
conf/cmi/core.entity_view_display.node.policymaker.default.yml
conf/cmi/core.extension.yml
conf/cmi/elasticsearch_connector.index.decisions.yml
conf/cmi/search_api.index.decisions.yml
conf/cmi/search_api.server.elasticsearch.yml
docker-compose.yml
public/modules/custom/paatokset_ahjo/migrations/paatokset_agenda_items.yml
public/modules/custom/paatokset_ahjo/paatokset_ahjo.module
public/modules/custom/paatokset_ahjo/src/Entity/AgendaItem.php
public/themes/custom/helfi_paatokset/templates/content/paatokset-issue.html.twig

Run `make new`
Make sure all db update ran with `drush updb`
Run paatokset_agenda_items -migration
Go to elastic index settings at /admin/config/search/search-api
Got to 'decisions' index settings and index all items (from the 'view' tab)
If you get an error with a message along the lines that you cannot connect to cluster, go to /admin/config/search/elasticsearch-connector, select the cluster and re-save the settings (this happens rarely)
Check that your elastic container is up and running with `docker-compose ps`. If it's down, run `sudo sysctl -w vm.max_map_count=524288` (happens on my machine, might not affect others)
Clone https://github.com/City-of-Helsinki/paatokset-search. Run `npm i` in root. Start dev server with `npm start`. Access the app at localhost:3000.
Check that …

PP-141: Add Elastic settings

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.routing.yml
public/modules/custom/paatokset_ahjo_api/src/Controller/AhjoSubscriberController.php

This adds a queue to handle subscriber callbacks from the Ahjo API and methods to debug the queue contents. Doesn't actually process anything yet, since we need to test what kind of data the API actually posts.
**To test:**
- Open this URL: https://helsinki-paatokset.docker.so/fi/ahjo_api/subscriber/test
- The data should contain an item_id
- Open this URL: https://helsinki-paatokset.docker.so/fi/ahjo_api/callback-queue
- This should list an item the with the same item_id you just saw
- Make a POST request with some form-data or x-www-form-urlencoded parameters to https://helsinki-paatokset.docker.so/fi/ahjo_api/subscriber/test
- Check the callback-queue URL again. The POST requests and the data you sent should be included in the list
- Send more …

PP-231: Add subscriber callback controller.

---

public/modules/custom/paatokset_ahjo_api/src/Plugin/Deriver/AhjoApiMigrationDeriver.php
public/modules/custom/paatokset_ahjo_openid/src/AhjoOpenId.php

**To test**
* Edit the env variable names in .env.local to use dashes instead of underscores (PAATOKSET-OPENID-SECRET and AHJO-PROXY-BASE-URL)
* Run `make up`
* Run `make shell` and then `printenv` to make sure the names were actually updated.
* Connect to VPN and make sure the authentication flow and token refreshing work here: https://helsinki-paatokset.docker.so/fi/admin/ahjo-open-id

PP-231: Convert env variable names to use dashes instead of underscores.

---

conf/cmi/core.entity_form_display.node.case.default.yml
conf/cmi/core.entity_view_display.node.case.default.yml
conf/cmi/core.entity_view_display.node.case.teaser.yml
conf/cmi/field.field.node.case.field_full_title.yml
conf/cmi/field.storage.node.field_diary_number.yml
conf/cmi/field.storage.node.field_diary_number_label.yml
conf/cmi/field.storage.node.field_full_title.yml
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_cases.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module

**To test**
* Run `drush updb; drush cim -y`
* Check that the case diary number fields have a max length of 255:
* https://helsinki-paatokset.docker.so/fi/admin/structure/types/manage/case/fields/node.case.field_diary_number
* https://helsinki-paatokset.docker.so/fi/admin/structure/types/manage/case/fields/node.case.field_diary_number_label/storage
* Change the `public/modules/custom/paatokset_ahjo_api/src/Plugin/Deriver/AhjoApiMigrationDeriver.php` file so that `ahjo_cases:all` points to `https://nginx-paatokset-test.agw.arodevtest.hel.fi/fi/ahjo-proxy/aggregated/cases_all`
* Run `drush cr; drush migrate-status ahjo_cases:all`. There should be about 499 unimported items
* Run `drush mim ahjo_cases:all`. This should complete without errors.
* Check the imported cases: …

PP-234: Update Case diary number fields and truncate long titles.

---

public/themes/custom/helfi_paatokset/package-lock.json
public/themes/custom/helfi_paatokset/package.json

This should fix most of these warnings, except the xmldom one which doesn't have a patched version: https://github.com/City-of-Helsinki/helsinki-paatokset/security/dependabot
**To test**
* Go to `/public/themes/custom/helfi_paatokset` and run `nvm use; nvm i`
* Test that the npm scripts work properly and the CSS compiles, etc. (`npm run build`, `npm run dev`, `npm run lint` and `npm run lint:js`)

PP-0: Fix packages based on dependabot warnings

---

composer.lock
conf/cmi/core.entity_view_display.meeting_video.meeting_video.default.yml
conf/cmi/core.extension.yml
conf/cmi/editor.editor.full_html.yml
conf/cmi/field.field.paragraph.accordion_item.field_accordion_item_content.yml
conf/cmi/search_api.index.decisions.yml
conf/cmi/search_api.settings.yml
public/modules/custom/paatokset_ahjo_api/src/Plugin/Deriver/AhjoApiMigrationDeriver.php
public/modules/custom/paatokset_ahjo_openid/src/AhjoOpenId.php

This includes a Drupal core security update, module updates and updates to hdbt + helfi_platform_config.
**To test**
- Run `make fresh` or `drush cr;drush updb;drush cim -y`
- Check that all modules are up-to-date: https://helsinki-paatokset.docker.so/en/admin/reports/updates
- Check that content from migrations doesn't break (policymakers, etc)
- Check if these blocks are now available after the hdbt / helfi_platform_config module updates: https://helsinkisolutionoffice.atlassian.net/browse/PP-241

PP-0: Drupal core and modules updates for 22.11.2021

---

conf/cmi/search_api.index.policymakers.yml
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/OrganJSON.php
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/SectorJSON.php

To test:
- Run `make new` or `drush cr && drush cim -y`
-  Check https://helsinki-paatokset.docker.so/fi/admin/config/search/search-api. There should be a new 'Policymakers' index.
- Go to https://helsinki-paatokset.docker.so/fi/admin/config/search/search-api/index/policymakers. Build the index data from the controls at the bottom of the page.

PP-238: Policymakers search

---

public/modules/custom/paatokset_policymakers/templates/block/block--policymaker-calendar.html.twig
public/themes/custom/helfi_paatokset/src/scss/components/block/_policymaker_calendar.scss

Ticket: https://helsinkisolutionoffice.atlassian.net/browse/PP-257
Fixed table structure according to comments specified in ticket. Fixed also mobile view that had some alignment issues.
How to test: 
Checkout branch and run `drush cr`. Go to some policymaker page i.ex. https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto and make sure it has some upcoming meetings (edit some to the future if not) so that the calendar will be visible on the page. 
Check the table structure that it is correct now.

PP-257: PP-257: fixed accessibility issues in policymaker calendar

---

conf/cmi/core.entity_form_display.node.trustee.default.yml
conf/cmi/core.entity_view_display.node.trustee.default.yml
conf/cmi/core.entity_view_display.node.trustee.teaser.yml
conf/cmi/field.field.media.declaration_of_affiliation.field__policymaker_reference.yml
conf/cmi/field.field.node.trustee.field_first_name.yml
conf/cmi/field.field.node.trustee.field_last_name.yml
conf/cmi/field.field.node.trustee.field_trustee_datapumppu_id.yml
conf/cmi/field.field.node.trustee.field_trustee_email.yml
conf/cmi/field.field.node.trustee.field_trustee_home_district.yml
conf/cmi/field.field.node.trustee.field_trustee_homepage.yml
conf/cmi/field.field.node.trustee.field_trustee_image.yml
conf/cmi/field.field.node.trustee.field_trustee_phone.yml
conf/cmi/field.field.node.trustee.field_trustee_profession.yml
conf/cmi/field.storage.node.field_trustee_datapumppu_id.yml
conf/cmi/field.storage.node.field_trustee_email.yml
conf/cmi/field.storage.node.field_trustee_home_district.yml
conf/cmi/field.storage.node.field_trustee_homepage.yml
conf/cmi/field.storage.node.field_trustee_image.yml
conf/cmi/field.storage.node.field_trustee_phone.yml
conf/cmi/field.storage.node.field_trustee_profession.yml

Ticket: https://helsinkisolutionoffice.atlassian.net/browse/PP-163
Added new fields for trustee that were specified in the ticket. As extra: separate first and last name fields were added.
Checkout branch and run `drush cim -y; drush cr`. Go to https://helsinki-paatokset.docker.so/fi/admin/structure/types/manage/trustee/fields and check the the new fields are visible as well as when creating a trustee https://helsinki-paatokset.docker.so/fi/node/add/trustee
Check code changes that there are no extra configs added

PP-163: PP-163: added more fields for trustee

---

conf/cmi/core.entity_view_display.node.meeting.default.yml
conf/cmi/core.entity_view_display.tpr_unit.tpr_unit.contact_card.yml
conf/cmi/core.entity_view_display.tpr_unit.tpr_unit.default.yml
conf/cmi/user.role.read_only.yml
public/modules/custom/paatokset_ahjo/js/meetings_calendar.js
public/modules/custom/paatokset_ahjo/templates/component/document.html.twig
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_trustees.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.info.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Service/MeetingService.php
public/modules/custom/paatokset_ahjo_api/templates/content/node--meeting.html.twig
public/modules/custom/paatokset_policymakers/js/policymaker_members.js
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

**To test**
* SSH into the container, then run `drush cim -y; drush cr; drush ap:fs -v; drush mim ahjo_trustees:all --update`
* If you don't have policymakers and meetings imported, run: `drush mim ahjo_policymakers:all; drush mim ahjo_meetings:all`
* Edit some kaupuningvaltuusto meetings with minutes and agendas published: https://helsinki-paatokset.docker.so/fi/admin/content/meetings?title=kaupunginvaltuusto&field_meeting_id_value=
* Change the meeting date so they are in 2022. Edit one of them to be tomorrow
* Go to the Kaupunginvaltuusto page: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto
*  The calendar should show the meetings you just edited. The motions and minutes links should take you to the minutes page of that meeting, not a pdf file
* …

PP-252 policymaker fixes

---

public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/PolicymakerSideNav.php

**To test**
* Checkout branch, run `make drush-cr` (assuming you have decisionmaker and meeting data imported)
* Go to the kaupunginvaltuusto page: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto
* The 'minutes of discussion' / 'keskustelupöytäkirjat' link should be visible in the subnavigation
* Open the documents page: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto/asiakirjat
* The dates listed should be the meeting date, not the minutes publication date (confirm this by opening on of the minute pages)
* On the minute page, the index and sections should now have an ndash separating them
* Go to the kaupunkiympäristölautakunta page: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunkiymparistolautakunta
* The minutes of discussion link …

PP-252: Minor decisionmaker fixes

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/templates/block/block--policymaker-listing.html.twig
public/modules/custom/paatokset_policymakers/paatokset_policymakers.module
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

**To test**
- If you don't have up-to-date policymaker and trustee data, ssh into the container and run `drush ap:fs -v;drush mim ahjo_decisionmakers:all;drush mim ahjo_trustees:all;drush mim ahjo_meetings:latest`
- Edit the kaupunginvaltuusto title: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto
- Open the Päättäjät listing page: https://helsinki-paatokset.docker.so/fi/paattajat (if this doesn't exist, create a landing page with the /paattajat URL alias).
- The kaupunginvaltuusto item should use the value from field_ahjo_title and no the edited title
- Scroll down to the "Viranhaltijat"-list. These should have the organization name field printed after the title. (This looks a bit ugly right now, but will be handled in the …

PP-165-260: Backend work for frontend tickets

---

conf/cmi/block.block.helfi_paatokset_page_title.yml
conf/cmi/block.block.paatoksetpolicymakermembers.yml
conf/cmi/core.entity_form_display.node.policymaker.default.yml
conf/cmi/core.entity_form_display.node.trustee.default.yml
conf/cmi/core.entity_view_display.node.policymaker.default.yml
conf/cmi/core.entity_view_display.node.trustee.default.yml
conf/cmi/field.field.node.policymaker.field_sector_name.yml
conf/cmi/field.storage.node.field_sector_name.yml
conf/cmi/search_api.index.decisions.yml
conf/cmi/search_api.index.policymakers.yml
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisionmakers.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/templates/block/block--policymaker-listing.html.twig
public/modules/custom/paatokset_policymakers/js/policymaker_members.js
public/modules/custom/paatokset_policymakers/paatokset_policymakers.module
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_policymakers/templates/block/block--policymaker-members.html.twig
public/modules/custom/paatokset_policymakers/templates/content/node--policymaker.html.twig

**To test**
* Checkout branch, SSH into the container and run: `drush cr; drush cim -y;drush mim ahjo_decisionmakers:all --update`
* Go to https://helsinki-paatokset.docker.so/kokouskalenteri and find some agenda or motion links for organizations that have spaces and dashes in the title. They should now take you to the correct page instead of a 404 error
* Go to https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto
* There should be a link to the members list in the links block
* The members list should work normally
* Go to: https://helsinki-paatokset.docker.so/fi/admin/content/decisionmakers
* Sort the list by organization type
* Open some "Luottamushenkilö"  or "Viranhaltija" decisionmakers. The members list should not be visible
* The "Viranhaltija" nodes should have …

PP-0: Misc decisionmaker fixes

---

composer.json
composer.lock
public/modules/custom/paatokset_search/paatokset_search.info.yml
public/modules/custom/paatokset_search/paatokset_search.services.yml
public/modules/custom/paatokset_search/src/EventSubscriber/PrepareIndex.php

Set up event subscriber that sets the default analyzer as 'finnish' in finnish indices.
To test:
- Delete your existing indices. This can be done by sending DELETE request to [elastic-url]/[index-name] - without any modifications to your local environment the url should look like http://localhost:9200/paatokset_decisions. You should get a response with message: `acknowledged: true`
- Run `make new`. Remember to take a backup with `make drush-create-dump` beforehand!
- Check that the index has been created. You can verify this by sending a GET request to http://localhost:9200/_cat/indices. The list should include `paatokset_decisions` -index.
- Send GET request to http://localhost:9200/paatokset_decisions/_settings. In the response under 'analysis' you should see that the default analyzer …

Pp 274 finnish analyzator

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module

Ticket: https://helsinkisolutionoffice.atlassian.net/browse/PP-283
Changed the order in which the initiatives lists are shown, latest year on the left and newest day first in the list
Checkout branch and run `drush cr`
Go to https://helsinki-paatokset.docker.so/fi/aloitteet
2022 should now be first in the list and i.ex. in 2021 listing December initiatives should be first

PP-283: Changed order in which initiatives are shown

---

conf/cmi/metatag.metatag_defaults.node.yml
conf/cmi/metatag.metatag_defaults.node__decision.yml
public/modules/custom/paatokset_search/paatokset_search.routing.yml

Note: This PR doesn't handle translating URLs or the title suffix yet, there's a separate ticket for translations etc.
**To test**
* Run `drush cr;drush cim -y`
* The decisions search should now be available at: https://helsinki-paatokset.docker.so/fi/asia
* Create a new node: https://helsinki-paatokset.docker.so/fi/node/add/landing_page
* After saving, the page title tag should be in this format: [node:title] | Päätökset | Helsingin Kaupunki
* Check an existing decision or create a new one (make sure to add a title and a organization name). The title should be in this format: [node:title] - [organization name] | Päätökset | Helsingin Kaupunki

PP-263: Change urls and titles

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php

This PR adds a new method for getting case node URLs with query parameters for decision nodes, or just decision node URLs if the case is missing.
**To test**
- Checkout branch and run `make drush-cr`
- If you don't have Ahjo data imported, run: `drush ap:fs;drush mim ahjo_decisionmakers:all;drush mim ahjo_meetings:latest;drush mim ahjo_cases:latest;drush mim ahjo_decisions:latest`
- This meeting should have decisions to test with: https://helsinki-paatokset.docker.so/fi/paattajat/tarkastuslautakunta/asiakirjat/U003110202118
- Check that each link actually links to the case node, not the decision node, and that the correct decision is loaded via the query parameter
- Delete one of the cases and reload the list. The link should now point to the decision node
- Find one of the decisions …

PP-0: Add method to caseService for getting full decision URLs

---

conf/cmi/core.entity_form_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.teaser.yml
conf/cmi/field.field.node.decision.field_decision_content_parsed.yml
conf/cmi/field.field.node.decision.field_decision_motion_parsed.yml
conf/cmi/field.storage.node.field_decision_content_parsed.yml
conf/cmi/field.storage.node.field_decision_motion_parsed.yml
conf/cmi/search_api.index.decisions.yml
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisions.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

**To test**
* SSH into the container and run `drush cr;drush cim -y`
* If you have decision data already, try running: `drush ap:dc -v`
* This should update the decision content and motion fields.
* Edit a few decisions from:  https://helsinki-paatokset.docker.so/fi/admin/content/decisions
* They should have HTML content in the decision and motion fields. The content should also be cleaned up a bit compared to the field_decision_content and field_decision_motion fields found in the decision data group (removed HTML and HEAD tags, and only including the main content for example).
* Run `drush migrate-rollback ahjo_decisions:latest;drush migrate-import ahjo_decisions:latest`
* OR if you didn't have decision data migrated, just run: `drush ap:fs -v;drush mim …

PP-288: Indexing for decision content and motion fields

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_api/src/Service/TrusteeService.php
public/modules/custom/paatokset_ahjo_api/templates/component/agenda-item--list-item.html.twig
public/modules/custom/paatokset_policymakers/src/Controller/PolicymakerController.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/PolicymakerSideNav.php
public/themes/custom/helfi_paatokset/helfi_paatokset.theme
public/themes/custom/helfi_paatokset/templates/content/node--trustee.html.twig

**To test**
- Run `make drush-cim;make drush-cr`
- If you don't have data from Ahjo imported yet, SSH into the container and run: `drush ap:fs;drush ahjo_meetings:latest;drush ahjo_cases:latest;drush ahjo_decisions:latest;drush ahjo_decisionmakers:all;drush ahjo_trustees:council;drush ap:ud --localdata`
- Find some decisions without a diary number: https://helsinki-paatokset.docker.so/fi/admin/content/decisions?title=&field_diary_number_value=&field_decision_native_id_value=&field_decision_motion_value=All&field_decision_content_value=All&order=field_diary_number&sort=asc
- The "Appeal process" accordion should not be visible and the layout shouldn't break
- Edit a meeting: https://helsinki-paatokset.docker.so/fi/node/689/edit
- In meeting data -> agenda, edit some of …

PP-276: Caseless decisions, agenda items without sequence numbers, document listing page titles

---

composer.json
composer.lock
conf/cmi/core.extension.yml
conf/cmi/editoria11y.settings.yml
conf/cmi/user.role.admin.yml
conf/cmi/user.role.anonymous.yml
conf/cmi/user.role.authenticated.yml
conf/cmi/user.role.content_producer.yml
conf/cmi/user.role.editor.yml
conf/cmi/user.role.read_only.yml

**To test**
- Checkout branch, run `make composer-install drush-cr drush-cim`
- Login as admin or content creator
- Navigate around the site. You should see the new icon in the bottom right corner
- Open a decision / case node. There should be some errors
- The example content pages should have some manual checks visible: https://helsinki-paatokset.docker.so/fi/esimerkkisivu
- Edit the example page and add a H6 heading somewhere in the content. Save the node. The module should notify you that the heading level jumped from H2 / H3 to H6.

PP-270: Install Editoria11y module

---

public/modules/custom/paatokset_policymakers/paatokset_policymakers.module

Ticket: https://helsinkisolutionoffice.atlassian.net/browse/PP-300
Checkout branch and run `drush cr`
Edit some policymaker page (i.ex. https://helsinki-paatokset.docker.so/fi/paattajat/yksikon-johtaja-henkilosto-ja-liiketoiminnan-tuki-yksikko) and add first and last names to it. The names should now appear after the initial title i.ex. "Yksikön johtaja: Etunimi Sukunimi"

PP-300: Added name to policymaker title if it is set

---

composer.json
composer.lock
public/modules/custom/paatokset_search/paatokset_search.libraries.yml

Bump paatokset_search to 1.0.0.
Jira: https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/PP/boards/172?modal=detail&selectedIssue=PP-304
(Make sure your index settings are up-to-date).
To test:
- `make shell` into the container. Run `composer update paatokset/paatokset_search  --no-cache`. This should update the application to version 1.0.0.
- Navigate to [policymakers page](https://helsinki-paatokset.docker.so/fi/paattajat). Try making a search that gets wildcard matches, eg. 'lääkäri'. You might want to ctrl / cmd + R to make sure browser cache does not produce weird stuff.
- Try clicking the latest item in the pagination. This should work as expected (takes you to the last page of results)
- Pagination shold be reflected in the URL (via 'results' -parameter). Try …

PP-304: Bump paatokset_search to 1.0.0

---

docker/openshift/crons/base.sh
docker/openshift/crons/run-aggregated-ahjo-integrations.sh
docker/openshift/crons/run-callback-queue.sh
docker/openshift/crons/run-helsinki-integrations.sh
docker/openshift/crons/run-immediate-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/SectorJSON.php
tools/make/project/ahjo.mk

This PR adds the remaining migrations to the cron job scripts. Also adds a fallback mechanism for missing cases and meetings, where they are added to the subscriber callback queue.
**To test**
* Read the shell scripts and check that they make sense. Any migrations missing?
* Run `drush cr;drush cim -y`
* If you have any migrated decision entities, roll them back with: `drush migrate-rollback ahjo_decisions:latest`
* Note: if this breaks because of URL redirects, delete the redirect and the node manually, then run `drush migrate-reset-status ahjo_decisions:latest` and continue the rollback.
* If you don't have migration data yet, run: `drush ap:fs;drush mim ahjo_decisions:latest`
* Run `drush ac:l`. The output should be mostly empty.
* Run `drush ap:ud --localdata -v`
* …

PP-305: Add missing cron jobs

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module

Go to https://helsinki-paatokset.docker.so/fi/paattajat and check that viranhaltihat accordions are alphabetically and that Viranhaltijat: Muut is now removed

PP-0: Removed muut from policymaker listing

---

conf/cmi/editor.editor.full_html.yml
conf/cmi/filter.format.full_html.yml

Add quote + table tool buttons to editor
Testing:
- Run `drush cim -y; drush cr`
- Create new content (or edit existing) with text type paragrapgs (ie. basic page). Add a new paragraph of type text and check that you can add quotes and tables from the toolbar at the top of the editor

PP-0: Editor settings

---

composer.json
composer.lock
conf/cmi/paatokset_helsinki_kanava.settings.yml
conf/cmi/paatokset_search.settings.yml
conf/cmi/search_api.index.decisions.yml
public/modules/custom/paatokset_helsinki_kanava/src/Form/HelsinkiKanavaForm.php
public/modules/custom/paatokset_search/paatokset_search.libraries.yml
public/modules/custom/paatokset_search/paatokset_search.links.menu.yml
public/modules/custom/paatokset_search/paatokset_search.routing.yml
public/modules/custom/paatokset_search/src/Form/PaatoksetSearchForm.php

Search filter changes:
- 'Viranhaltijat' -filter now shows decisions where organization_type is correct value
-  Decisionmaker-filter accepts single value only
- Date displayed on the decision card is now the meeting date
To test:
- `make shell` into the container. Run `composer update paatokset/paatokset_search; drush cim -y; drush cr`
- Navigate to your (decisions index page)[https://helsinki-paatokset.docker.so/fi/admin/config/search/search-api/index/decisions]. Reindex all the content (Queue all items for reindexing -> run indexing process). It _might_ be good to clear all indexed data before reindex, if your local data has changed noticeably since last indexing.
-  Once indexing is complete, navigate to (search page)[https://helsinki-paatokset.docker.so/fi/asia].
Check following on …

Pp 330 search filter changes

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Plugin/Block/AllInitiativesBlock.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/Block/DecisionTreeBlock.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/Block/FrontpageCalendarBlock.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/Block/MeetingsCalendarBlock.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/Block/PolicymakerListingBlock.php
public/modules/custom/paatokset_policymakers/paatokset_policymakers.module
public/modules/custom/paatokset_policymakers/src/Controller/PolicymakerController.php
public/modules/custom/paatokset_policymakers/src/Plugin/Block/CalendarBlock.php
public/modules/custom/paatokset_policymakers/src/Plugin/Block/ContactsBlock.php
public/modules/custom/paatokset_policymakers/src/Plugin/Block/MembersBlock.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/AgendasSubmenuBlock.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/DocumentsBlock.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/MinutesOfDiscussionBlock.php
public/themes/custom/helfi_paatokset/helfi_paatokset.theme

This PR adds missing cache tags to multiple blocks and node preprocesses to content list caches can be invalidated properly.
- Checkout branch and run `make drush-cr`
- If you don't have any integration data, run `make ahjo-migrations`
- Comment out everything related to caches in `public/sites/default/local.settings.php`, then run `make drush-cr` again
- Login as admin to the site in one window and open another window in incognito mode. Whenever you need to test a specific page, test it in both
- Open the frontpage: https://helsinki-paatokset.docker.so/fi/etusivu
- Find one of the meetings listed in the frontpage calendar and edit it: https://helsinki-paatokset.docker.so/fi/admin/content/meetings
- Edit the date, toggle the "agenda published / minutes published" and change the "Decision …

PP-280: Add cache tags to custom content lists

---

public/modules/custom/paatokset_search/src/Plugin/search_api/processor/ColorClass.php

Fix decision indexing to pass id of policymaker to `getPolicymakerClassById` rather than passing the decision node to `getPolicymakerClass`.

PP-0: Retrieve color class by dm id

---

conf/cmi/core.entity_view_display.node.page.default.yml

Enable toc on basic pages.
To test:
- `make drush-cim; make drush-cr`
- Open up a basic page with h2-elements or create one. (If you have data from testing, https://helsinki-paatokset.docker.so/fi/tietoa-paatoksenteosta/kuka-paattaa-ja-mista is a good one)
- Edit the page -> enable the table of contents toggle and enter value to **Table of contents title**
- View the page. Table of contents should be generated to the top of the page.

PP-0: Add toc field to page content

---

public/modules/custom/paatokset_ahjo_api/src/Service/MeetingService.php
public/modules/custom/paatokset_ahjo_api/templates/component/document.html.twig
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_policymakers/templates/content/minutes.html.twig

**Replicate issues**
- **Before checking out the branch**, run `make drush-cr ahjo-migrations drush uli` (make sure you have the ahjo local proxy url pointing to test so you can get latest data)
- Run these migration commands in the container:
- `drush ap:update meetings 00400202210 -v`
- `drush ap:update meetings 00400202211 -v`
- `drush ap:update meetings 00400202212 -v`
- Check the Kaupunginhallitus page: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginhallitus
- There should be only one item in the recent documents list
- Add meeting minutes to one Kaupunginvaltuusto meeting: https://helsinki-paatokset.docker.so/fi/media/add/minutes_of_the_discussion
- Find the meeting and open its minutes page: https://helsinki-paatokset.docker.so/fi/admin/content/meetings?title=kaupunginva …

PP-337: Minutes of discussion fixes

---

conf/cmi/core.entity_form_display.node.meeting.default.yml
conf/cmi/core.entity_view_display.node.meeting.default.yml
conf/cmi/core.entity_view_display.node.meeting.teaser.yml
conf/cmi/field.field.node.meeting.field_meeting_date_original.yml
conf/cmi/field.storage.node.field_meeting_date_original.yml
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_meetings.yml
public/modules/custom/paatokset_ahjo_api/src/Service/MeetingService.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_policymakers/templates/block/block--policymaker-calendar.html.twig

**To test**
- Before checking out branch, import meeting data with: `make ahjo-migrations`
- Also add the test site ahjo proxy url and run `make up` so you can fetch latest meeting data
- Checkout branch, login to container and run `drush cr;drush cim -y;`
- Check some meetings: https://helsinki-paatokset.docker.so/fi/admin/content/meetings
- There should be a new "Meeting date (original)" field, but it should be empty
- Check the Kaupunginvaltuusto page: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto
- The "Additional information / Lisätietoja" field should be empty
- Run `drush ap:rmod -v` and try to edit some meetings again. This should fill in the current meeting date as the original value.
- Edit a Kaupunginvaltuusto meeting that is visible in the calendar block …

PP-327 origin meeting date field and moved meeting status

---

conf/cmi/language/fi/system.site.yml
conf/cmi/language/sv/metatag.metatag_defaults.node__decision.yml
conf/cmi/language/sv/system.site.yml
conf/cmi/metatag.metatag_defaults.global.yml
conf/cmi/metatag.metatag_defaults.node.yml
conf/cmi/metatag.metatag_defaults.node__decision.yml
conf/cmi/openid_connect.client.tunnistamo.yml
conf/cmi/system.site.yml
conf/cmi/user.role.read_only.yml

**To test**
- Edit or create the frontpage and add translations for en and sv versions. Make sure the URL alias is /etusivu for all of them
- Run `make drush-cr drush-cim`
- Open the frontpage on all languages.
- The site name should be "Decisions", "Päätökset" or "Beslut".
- The title attribute should be "[frontpage title] | Päätökset | Helsingin kaupunki", "[frontpage title] | Decisions | City of Helsinki" or "[frontpage title] | Beslut | Helsingfors stad"
- Open the 404 page (to test non node metatags)
- The title attribute should be: "Sivua ei löydy | Päätökset | Helsingin kaupunki", "Page not found | Decisions | City of Helsinki" or "Sidan hittades inte | Beslut | Helsingfors stad"

PP-345: Site name translation

---

public/modules/custom/paatokset_policymakers/js/policymaker_members.js
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/themes/custom/helfi_paatokset/helfi_paatokset.theme

**Replicate issue:**
- Before checking out the branch
- If you don't have data imported, run the following commands in the container. You'll need the ahjo local proxy url env variable to point to test for these.
- `drush migrate-import ahjo_decisionmakers:all`
- `drush ap:update meetings 0290020224 -v`
- `drush ap:update meetings U11500202124 -v`
- Open the kaupunginvaltuusto page and the composition JSON: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto and https://helsinki-paatokset.docker.so/fi/ahjo_api/org_composition/02900
- Scroll down to the members list and toggle the "Show deputies" option
- The "Deputy of" field should not be visible for the members that show up
- The composition should have multiple members where the "DeputyOf" field is "null null" as a …

PP-335: Hide null deputy info

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module

**To test**
- To get up-to-date initiative data, ssh to the container and run: `drush mim ahjo_trustees:council --update` (you'll need the proxy URL environment variable for this)
- Go to https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto/aloitteet OR create a page with /aloitteet as the URL alias
- The initiatives should be sorted from newest to oldest and the year tabs should be in the correct order

PP-0: Fix sorting order on all initiatives list.

---

public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

**To test**
- Run `make new` (take a backup of your local site to save your current setup)
- SSH into the container and run `drush ahjo-proxy:create-site-structure`
- This should create some nodes and menu items for the basic site structure (frontpage, decisionmakers, calendar, etc)

PP-0: Add new command for creating site structure.

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

**Replicate issue before checking out branch:**
* Optional: Run `make new` to make testing clearer
* Login to the container and run the following commands (you'll need the proxy url env variable)
* `drush ap:update organization 00400 -v`
* `drush ap:update organization U02980 -v` 
* `drush ap:update meetings U0298020224 -v` (if this meeting already has minutes published, pick another one that only has the agenda)
* `drush ap:update meetings 00400202216 -v`
* Run  the command for generating motions: `drush ap:gm -v`
* This should generate motions for all agenda items of the meeting your imported (this is easier to test if you ran `make new`).
* Reset the meeting status and generate motions again: `drush ap:rm -v;drush ap: gm -v`
* This should skip all the agenda items with diary numbers, …

PP-360: Better creation of motions and matching of decisions to motions.

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

**To test**
- Run `make drush-cr`
- Import the following decisions and meetings:
- `drush ap:update decisions {EEE8CF3C-FF11-4006-A793-FFCC89BBB608} -v`
- `drush ap:update decisions {FE649278-C812-C96D-B0E7-75DF96700001} -v`
- `drush ap:update cases HEL-2021-010378 -v`
- `drush ap update meetings 8100020177 -v`
- `drush ap:update meetings U540100202119 -v`
- Open the this decision: https://helsinki-paatokset.docker.so/fi/asia/hel-2021-010378/fe649278-c812-c96d-b0e7-75df96700001
- The policymaker name should be visible and should have the default color-sumu color coding
-  Even though the meeting has been imported, the "see other decisions" link should not be visible because the policymaker node does not exist
- Edit the decision node and add ?HEL-2021-010378` as the case …

PP-353: Display default name for on decision if policymaker node is missing

---

public/modules/custom/paatokset_ahjo_api/config/install/paatokset_ahjo_api.default_texts.yml
public/modules/custom/paatokset_ahjo_api/config/schema/paatokset_ahjo_api.schema.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Form/DefaultTextSettingsForm.php
public/modules/custom/paatokset_ahjo_api/src/Service/TrusteeService.php
public/modules/custom/paatokset_ahjo_api/templates/block/block--policymaker-listing.html.twig
public/themes/custom/helfi_paatokset/helfi_paatokset.theme

This PR changes default translation texts from finnish to english.
**To test**
* Checkout branch, run `make drush-cr drush-cim`
* Open the decisionmakers page: https://helsinki-paatokset.docker.so/fi/paattajat
* All the main headings and accordion titles should be in english now
* Check that the headings can be translated: https://helsinki-paatokset.docker.so/fi/admin/config/regional/translate
* Open the decision tree page: https://helsinki-paatokset.docker.so/fi/tietoa-paatoksenteosta
* The texts should be in english
* The links should be `fi/paattajat` by default and editable in the default texts settings: https://helsinki-paatokset.docker.so/fi/admin/tools/default-texts
* Try changing the links to something and check that the changes appear on the page
* The texts should be …

PP-349: Unify translations

---

composer.lock
conf/cmi/core.entity_form_display.node.decision.default.yml
conf/cmi/core.entity_form_display.node.meeting.default.yml
conf/cmi/core.entity_view_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.teaser.yml
conf/cmi/core.entity_view_display.node.meeting.default.yml
conf/cmi/core.entity_view_display.node.meeting.teaser.yml
conf/cmi/field.field.node.decision.field_outdated_document.yml
conf/cmi/field.field.node.meeting.field_decisions_checked.yml
conf/cmi/field.storage.node.field_decisions_checked.yml
conf/cmi/field.storage.node.field_outdated_document.yml
docker/openshift/crons/run-immediate-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

This PR makes the motions -> decision update path better. Previously some decision records weren't updated because there was data remaining from the motion phase.
This PR also adds checks to make sure all motions and decisions are created for meetings.
**Test decision record fetching**
- Run `make new` to make testing easier (take a database backup of your previous state if you wish to return to it)
- Import some organizations and decisions to test with:
- `drush ap:update organization U540200 -v`
- `drush ap:update organization U02978 -v`
- `drush ap:update meetings U540200202211 -v` (This should be a meeting with only agenda published, not minutes). Replace the ID with another meeting if this has been updated).
- `drush ap:update meetings U0297820227 -v`
- Edit both meetings and set the …

PP-379: Handle motions to decisions updates

---

public/modules/custom/paatokset_policymakers/paatokset_policymakers.module
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerLazyBuilder.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_policymakers/templates/component/policymaker-cards.html.twig
public/modules/custom/paatokset_submenus/src/Plugin/Block/PolicymakerSideNav.php

This adds better support for localizing organization titles and URLs, and removes finnish words from untranslated URLs.
**To test**
- Checkout branch, run `make drush-cr drush-cim`
- Run `make ahjo-migrations` if you don't have ahjo data
- Read through the code changes
**Fully translated organization**
- Run `drush ap:update organization 02900 -v;drush ap:update organization_sv 02900 -v`
- Make sure you have added this organization to the menu under "Päättäjät"
- Create some test pages and add them menu links under the organization
- Create some test pages and add them as custom links under this organization
- Create an english translation of the page manually (delete the previous one if it was already translated)
- Change the title to "Helsinki City Council": …

PP-378: English language decisionmaker URLs

---

public/modules/custom/paatokset_ahjo_api/src/Service/TrusteeService.php
public/themes/custom/helfi_paatokset/helfi_paatokset.theme
public/themes/custom/helfi_paatokset/templates/content/node--trustee.html.twig

**To test**
- Make sure you have councillors and meetings from the Ahjo API: `make ahjo-migrations`
- Check out some councillors: https://helsinki-paatokset.docker.so/fi/admin/content/trustees
- Compare the printed data to what's in the node and what's in the organization meeting compositions
- Read the code changes
- Is this a reasonable way to fetch and iterate this data from the database?
- Can you think of a more efficient way to get this data? Could this cause issues in the production environment?

PP-268: Get councillor memberships and roles

---

public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_ahjo_proxy/src/Controller/AhjoProxyController.php

This MR adds minor script improvements and 404 errors for API monitoring purposes.
**To test**
- Before checking out the branch, go to:
- https://helsinki-paatokset.docker.so/fi/ahjo-proxy/meetings
- https://helsinki-paatokset.docker.so/fi/ahjo-proxy/cases
- https://helsinki-paatokset.docker.so/fi/ahjo-proxy/decisions
-  These should return empty JSON results with a 200 OK status code (at least if you have VPN off).
- Reload the ahjo-proxy URLs. These should now return 404 errors.
- If you can get the local API connection to work, connect to VPN and authenticate with the API: https://helsinki-paatokset.docker.so/fi/admin/ahjo-open-id
- Reload the pages again. You should get a proper response this time. (If you don't get the connection working we can …

PP-380: Throw 404 error if proxy returns an error.

---

composer.json
composer.lock
conf/cmi/core.entity_form_display.node.policymaker.default.yml
conf/cmi/core.entity_view_display.media.ahjo_document.media_library.yml
conf/cmi/core.entity_view_display.media.declaration_of_affiliation.media_library.yml
conf/cmi/core.entity_view_display.media.file.media_library.yml
conf/cmi/core.entity_view_display.media.image.default.yml
conf/cmi/core.entity_view_display.media.image.image_with_caption.yml
conf/cmi/core.entity_view_display.media.image.media_library.yml
conf/cmi/core.entity_view_display.media.minutes_of_the_discussion.media_library.yml
conf/cmi/core.entity_view_display.media.policymaker_images.default.yml
conf/cmi/core.entity_view_display.media.policymaker_images.media_library.yml
conf/cmi/core.entity_view_display.media.remote_video.media_library.yml
conf/cmi/core.entity_view_display.media.soundcloud.media_library.yml
conf/cmi/core.entity_view_display.node.trustee.default.yml
conf/cmi/core.entity_view_display.paragraph.contact_card.default.yml
conf/cmi/core.entity_view_display.tpr_unit.tpr_unit.contact_card.yml
conf/cmi/core.entity_view_display.tpr_unit.tpr_unit.default.yml
conf/cmi/core.extension.yml
conf/cmi/editor.editor.full_html.yml
conf/cmi/media.type.remote_video.yml
conf/cmi/simple_sitemap.sitemap.index.yml
conf/cmi/simple_sitemap.type.index.yml
conf/cmi/views.view.media.yml
conf/cmi/views.view.media_library.yml
docker/openshift/crons/run-aggregated-ahjo-integrations.sh

**To test:**
- Checkout branch, run `make fresh` (take a database backup first)
- Run `make ahjo-migrations` to get some decisions content (if you don't have any)
- Make sure you have indexed content in the decisions index: https://helsinki-paatokset.docker.so/fi/admin/config/search/search-api/index/decisions
- Follow these test instructions on the decisions search page: https://github.com/City-of-Helsinki/paatokset-search/pull/22
- Check that there are no pending security updates: https://helsinki-paatokset.docker.so/en/admin/reports/updates
- Click around the site and check that decision and organization related content works as it should
**Updates:**
```
- Upgrading commerceguys/addressing (v1.3.0 => v1.4.1)
- Upgrading composer/ca-bundle (1.3.2 => 1.3.3)
- Upgrading composer/composer …
```

PP-255: Drupal core and modules updates, Search app update

---

public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisions.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

This PR enables swedish language motion generation and adds some fixes to the motion -> decision conversion to make it work with multiple languages.
**To test:**
- Create a database dump with your current status and change the filename (so the dump doesn't get overridden) if you want to return to it later
- Checkout branch, run `make new` to start from scratch (we need old meetings for testing and your local might have updated versions of these)
- Login to the test environment and create a new user with the "API User" role and get the user's API Key from the key authentication tab. (You can also get this from Juho if you can't create new users or the role is not visible)
- Do the same in your local environment. Save the API keys in a text file so you have access to both
**Fetch old …

PP-352: Decision migration changes

---

conf/cmi/core.entity_form_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.teaser.yml
conf/cmi/field.field.node.decision.field_dates_checked.yml
conf/cmi/field.storage.node.field_dates_checked.yml
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisions.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.links.action.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.links.menu.yml
public/modules/custom/paatokset_ahjo_api/src/DisallowedDecisionsListBuilder.php
public/modules/custom/paatokset_ahjo_api/src/DisallowedDecisionsStorageManager.php
public/modules/custom/paatokset_ahjo_api/src/Entity/DisallowedDecisions.php
public/modules/custom/paatokset_ahjo_api/src/Form/DisallowedDecisionsDeleteForm.php
public/modules/custom/paatokset_ahjo_api/src/Form/DisallowedDecisionsForm.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/migrate/process/SkipDisallowedDecisions.php
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

This PR adds a new configuration entity for blocking specific decisions based on Org ID, year and section number from being migrated and a new drush command for cleaning up disallowed decisions that have already been migrated. This also includes the PP-407 ticket with updated decision date handling.
**To test**
* Checkout branch, run `make composer-install drush-cr drush-cim`
* Check that the configuration entity form is accessible: https://helsinki-paatokset.docker.so/fi/admin/config/system/disallowed-decisions
* Migrate the "all" dataset from test environment: `drush migrate-import ahjo_decisions:all --update`
* This should get data from the beginning of 2018 with 838 decisions. If you get a different dataset, ask Juho for more info
* Open the decisions list: …

PP-376: Decision mass removal

---

composer.json
composer.lock
conf/cmi/core.extension.yml
public/modules/custom/paatokset_ahjo_api/src/Service/TrusteeService.php
public/modules/custom/paatokset_council_info/paatokset_council_info.info.yml
public/modules/custom/paatokset_council_info/paatokset_council_info.links.menu.yml
public/modules/custom/paatokset_council_info/paatokset_council_info.routing.yml
public/modules/custom/paatokset_council_info/src/Form/InfoImportForm.php

This PR adds a new form for importing council member data from a CSV file.
**To test**
- The excel file can be found in the ticket: https://helsinkisolutionoffice.atlassian.net/browse/PP-399
- Download the file and save it as an CSV. Use `;` as the delimiter
- Run `make fresh`, `make new` or `make composer-install drush-cim drush-cr`
- Composer install is needed for a new CSV parsing library
- SSH into the container and run `drush migrate-import ahjo_trustees:council --update`
- Login as admin and go to https://helsinki-paatokset.docker.so/fi/admin/config/system/council-import
- Select the CSV file and upload it
- The excel has info on people who aren't council members at the moment, so not all of the data can be imported
- Check the logs for more info on which nodes …

PP-399: Councilmember info import form CSV file

---

docker/openshift/crons/run-aggregated-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

This PR adds a new drush command for checking all organization and office holder statuses and marks the as inactive if they are no longer existing.
**To test**
- SSH in to the container and import decisionmaker content: `drush migrate-import ahjo_decisionmakers:all;drush migrate-import ahjo_decisionmakers:all_sv`
- Run these commands to get a decision from an inactive office holder:
- `drush ap:update cases HEL-2021-010957 -v; drush ap:update decisions {F32B8346-CAA4-46F3-99FD-780973D211A2} -v`
- Run the command: `drush ahjo-proxy:check-dm-status -v` (this will take about 20 minutes)
- Check the output from the command. Find the inactive nodes from: https://helsinki-paatokset.docker.so/fi/admin/content/decisionmakers
- Open one of the inactive nodes. …

PP-402: Handle dissolved decisionmakers

---

conf/cmi/config_ignore.settings.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.routing.yml
public/modules/custom/paatokset_ahjo_api/src/Form/DefaultTextSettingsForm.php
public/modules/custom/paatokset_ahjo_proxy/paatokset_ahjo_proxy.links.menu.yml
public/modules/custom/paatokset_ahjo_proxy/paatokset_ahjo_proxy.routing.yml
public/modules/custom/paatokset_ahjo_proxy/paatokset_ahjo_proxy.services.yml
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Form/AhjoProxyBlacklistForm.php
public/modules/custom/paatokset_ahjo_proxy/src/Form/AhjoProxyManualCacheForm.php

**To test**
- Checkout branch, run `make drush-cr drush-cim`
- Check that these forms exist and that they both work:
- https://helsinki-paatokset.docker.so/fi/admin/config/services/ahjo-blacklist
- https://helsinki-paatokset.docker.so/fi/admin/config/services/ahjo-manual-cache
- It's enough that the form can be submitted and that it shows messages about adding and removing URLs from cache. It can't be tested locally.
- Add values to the blacklist form, then run `make drush-cex`. It should show that some values will be exported
- Change the values in the form again, then run `make drush-cim`. This should NOT override the values you just changed because of config ignore.

PP-409: Entity blacklist and cache forms

---

conf/cmi/field.field.node.organization.field_organization_data.yml
conf/cmi/field.field.node.organization.field_policymaker_id.yml
conf/cmi/language.content_settings.node.organization.yml
public/modules/custom/paatokset_ahjo_api/src/Commands/AhjoCallbackCommands.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/QueueWorker/AhjoOrgChartQueueWorker.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_ahjo_proxy/src/Controller/AhjoProxyController.php

**To test**
- Checkout branch, run `make drush-cr drush-cim`
- Run the following commands to fetch the finnish organization chart: `drush ahjo-callback:start-org-queue 00001 10 -v`
- Confirm that it was added to the queue by running: `ahjo-callback:list-org-queue` then run `drush queue:run ahjo_api_org_queue -v` (this will take a while)
- Check the organization endpoint data: https://helsinki-paatokset.docker.so/fi/ahjo-proxy/org-chart/00001/10 (you have to be logged in for this URL to work)
- Check the swedish version and confirm that it shows finnish nodes: https://helsinki-paatokset.docker.so/sv/ahjo-proxy/org-chart/00001/10 (Each object has "Language: fi" and the names should be in finnish)
- Fetch the swedish translations of the organizations:  `drush ahjo-callback:start-org-queue …

PP-0:  Org chart language functionality

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php

**Before checking out the branch:**
- SSH into the container with: `make shell`
- Inside the container, run: `drush ap:update decisions 46d4100a-3421-48bf-b22f-d3078b3890bf -v;drush ap:ud -v`
- Open this decision: https://helsinki-paatokset.docker.so/fi/asia/hel-2022-003453/46d4100a-3421-48bf-b22f-d3078b3890bf
- There should be an attachment with the title "Non-public" and an eye icon
**To test**
- Reload the decision page
- The non-public attachment title should change to: "Non-public: JulkL (621/1999) 24.1 § 20 k"

PP-390: Add securityreasons field to decision attachments.

---

conf/cmi/core.entity_form_display.node.article.default.yml
public/themes/custom/helfi_paatokset/helfi_paatokset.theme

This changes the way article publication date and time are displayed.
**To test**
- Run `make drush-cr drush-cim` (run `make new` if you run into issues with config import)
- Create new articles and follow these test cases: https://helsinki-paatokset.docker.so/fi/node/add/article
- Create one article and set it to be published in a few minutes when you're still creating it.
- Create one article as unpublished. Then edit it and schedule it to be published in a few minutes.
- Create one article and publish it. Edit it and set it to be published in a few minutes (this should unpublish the article).
- For all of these, the time should be the time the node was created, not yet the scheduled publication time.
- Wait until a minute or two past the scheduled time, ssh into the container with …

PP-435: Article publish date fixes

---

docker/openshift/crons/run-immediate-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_api/js/meetings_calendar.js
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_cases.yml
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisions.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_api/src/Service/MeetingService.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_helsinki_kanava/src/Plugin/Block/AnnouncementsBlock.php
public/modules/custom/paatokset_policymakers/paatokset_policymakers.module
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/TopCategoryCode.php
public/modules/custom/paatokset_search_form/src/Form/AdvancedSearchForm.php
public/modules/custom/paatokset_search_form/src/Form/PaatoksetSearchForm.php
public/themes/custom/helfi_paatokset/templates/components/decision-voting-results.html.twig

**To test**
- Checkout branch and run `make drush-cr drush-cim` (if this gives you any errors, run `make new`).
- Get data for testing. Login to the container with`make shell` and then run `drush migrate-import ahjo_decisionmakers:all && drush migrate-import ahjo_meetings:latest && drush migrate-import ahjo_decisions:latest && drush ap:update decisions 2160018e-a7a3-c116-8414-832121f00003 -v && drush ahjo-proxy:update-decisions -v && drush queue:run ahjo_api_subscriber_queue -v && drush ahjo-proxy:update-decisions --update -v`
- While the imports are running, read the code changes and make sure there's nothing unclear or things that should be refactored
- Go to https://helsinki-paatokset.docker.so/fi/admin/content/decisions and filter for swedish language decisions
- Edit some of them and …

PP-433: Translation fixes

---

conf/cmi/config_ignore.settings.yml
conf/cmi/metatag.metatag_defaults.global.yml
conf/cmi/paatokset_ahjo_proxy.settings.yml
public/modules/custom/paatokset_ahjo_proxy/config/install/paatokset_ahjo_proxy.settings.yml
public/modules/custom/paatokset_ahjo_proxy/config/schema/paatokset_ahjo_proxy.schema.yml
public/modules/custom/paatokset_ahjo_proxy/paatokset_ahjo_proxy.links.menu.yml
public/modules/custom/paatokset_ahjo_proxy/paatokset_ahjo_proxy.routing.yml
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_ahjo_proxy/src/Form/AhjoProxySettingsForm.php

**Setup**
- Checkout branch, run `make drush-cim drush-cr` (Run `make new` if you run into any issues)
**Testing robots metatag:**
- Create a few test pages. Also create a frontpage node if you don't have it locally (`/etusivu`)
- Check the pages HTML source for metatags. You should find `<meta name="robots" content="noindex, nofollow, noarchive, nosnippet, noodp, noydir, noimageindex, notranslate" />` in the source.
- Also check that the same metatag is found on the 404 page
- Check that the search page (which is not a node) has the same metatags: https://helsinki-paatokset.docker.so/fi/asia
- Log into the container with `make shell` and import some content with `drush migrate-import ahjo_decisionmakers:all && drush migrate-import ahjo_trustees:council && drush migrate-import …

PP-422 & PP-443: Fixes for Ahjo API HYTE integration, Disallow indexing for all pages

---

public/modules/custom/paatokset_search/paatokset_search.routing.yml
public/modules/custom/paatokset_search/src/Controller/SearchController.php
public/modules/custom/paatokset_search/src/Controller/SearchProxyController.php
public/modules/custom/paatokset_search/src/Plugin/Block/PolicymakerSearchBlock.php
public/modules/custom/paatokset_search_form/src/Plugin/Block/SearchBlock.php

Temporary solution because elasticsearch proxy is not public on prod. This passes the requests through Drupal to the proxy.
**To test**
- Checkout branch, run `make composer-install drush-cr`
- Make sure your .env.local file contains these: 
```
REACT_APP_ELASTIC_URL=https://paatokset-proxy-test.agw.arodevtest.hel.fi
REACT_APP_PROXY_URL=https://helsinki-paatokset.docker.so/fi/search-proxy
```
- Run `make up`
- Go to https://helsinki-paatokset.docker.so/fi/etusivu (create the page if it doesn't exist)
- Make sure the autocomplete suggestions work
- Go to https://helsinki-paatokset.docker.so/fi/asia
- Try out some searches and make sure the application works as intended
- Open the network panel in your developer toolbar. All search related requests should go to …

PP-0: Add internal proxy URL for search.

---

public/modules/custom/paatokset_ahjo_api/src/Plugin/QueueWorker/AhjoCallbackQueueWorker.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php

**To test**
- Checkout branch, run `make drush-cim drush-cr` (if you get errors, just run `make new`)
- Go to https://paatokset.hel.fi/fi/kokouskalenteri and find an upcoming meeting with a published agenda (has a "Avaa esityslista" link).
- Open the meeting and copy its ID: paatokset.hel.fi/fi/paattajat/kaupunginvaltuusto/asiakirjat/**0290020231**
- SSH into the container with `make shell`
- Import the meeting locally: `drush ap:update meetings 0290020231 -v` (replace the meeting ID with the one you found).
- Run `drush ap:gm -v` to process the motions. The message should say that at least one node was found and it should process multiple items
- Check https://helsinki-paatokset.docker.so/fi/admin/content/decisions?field_is_decision_value=0 to see that the motions were actually created
- …

PP-462: Trigger meeting motion regeneration after update

---

public/modules/custom/paatokset_policymakers/src/Service/PolicymakerLazyBuilder.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/themes/custom/helfi_paatokset/helfi_paatokset.theme
public/themes/custom/helfi_paatokset/templates/content/node--article--full.html.twig

This MR fixes some content sorting and adds a scheduled unpublish message to articles.
**To test**
- Checkout branch, run `make drush-cr` (or `make new').
- Run the following commands to import content for testing:
```
drush mim ahjo_decisionmakers:all --update
drush ap:update meetings 02900202021 -v
drush ap:update meetings 02900202122 -v
drush ap:update meetings 02900202221 -v
drush ap:update meetings 02900202212 -v
```
- Add some minutes of discussion PDF files: https://helsinki-paatokset.docker.so/fi/media/add/minutes_of_the_discussion
- Add one for each of the Kaupunginvaltuusto meetings that were imported above
- Add them in a random order (for example: 2018, 2022, 2021) so we can test that the sorting works
- Go to: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuust …

PP-458: Misc fixes

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

This PR fixes decision sorting on multiple pages. Correct logic:
- Decisions should be sorted by date, newest first
- If the date is the same, decisions should be sorted by their section number, largest first. These are added sequentially each year, so larger = newer.
**Replicate issue, get data for testing:**
- Before checking out branch, pull in data for testing:
```
drush ap:update cases hel-2022-008625 -v
drush ap:update organization u511052007020vh1 -v
drush ap:update decisions ca6edb1d-f4cf-42bf-8704-8c70b0ae6f08 -v
drush ap:update decisions 1aa1e916-8f27-4a00-97eb-cdda61fda9cb -v
drush ap:update decisions 94d3906c-5e5c-48e9-b692-5bf5664bd6a6 -v
drush ap:update decisions af277802-02e5-44c1-8eeb-c695525c8515 -v
drush ap:update decisions 3efc18e0-12fd-c3af-883a-822413400001 -v
drush …
```

PP-0: Try to fix office holder decision sorting.

---

conf/cmi/core.entity_form_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.teaser.yml
conf/cmi/field.field.node.decision.field_decision_series_id.yml
conf/cmi/field.storage.node.field_decision_series_id.yml
conf/cmi/views.view.decisions.yml
docker/openshift/crons/run-immediate-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisions.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

**To test**
* Run `make new`
* Go to `public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisions.yml` and remove the lines 140 - 144 ( the `_skip_if_series_id_is_empty` step). Run `make drush-cr`
* Login to the container and import decisions:
* `drush ap:update decisions {167D3993-E3AE-4E53-AF12-6431179EF3E2} -v`
* `drush ap:update decisions {56763595-69AB-CC78-85C4-831B42900000} -v`
* Go to https://helsinki-paatokset.docker.so/fi/admin/content/decisions?status=All
* You should see two decisions with the same title
* Rollback and import decisions again, but this time fetch missing data to the first one:
* `drush migrate-rollback ahjo_decisions:single`
* `drush ap:update decisions {167D3993-E3AE-4E53-AF12-6431179EF3E2} -v`
* `drush ap:ud -v`
* `drush ap:update …

PP-453: Decision migration fixes with Series ID field

---

conf/cmi/core.entity_form_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.default.yml
conf/cmi/core.entity_view_display.node.decision.teaser.yml
conf/cmi/field.field.node.decision.field_status_checked.yml
conf/cmi/field.storage.node.field_status_checked.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

**To test**
- Checkout branch, run `make new`
- Go to `public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisions.yml` and remove the lines 140 - 144 ( the _skip_if_series_id_is_empty step). Run `make drush-cr`
- Migrate the following decisions:
```
drush ap:update {167D3993-E3AE-4E53-AF12-6431179EF3E2} -v
drush ap:update {80A6CFE9-F663-455B-B771-E06C7FCCED57} -v
drush ap:update {29150CA1-2059-C4E7-90DC-830CC2300003} -v
drush ap:update {56763595-69AB-CC78-85C4-831B42900000} -v
drush ap:update {F1302096-A870-4849-BBB1-AC52ACF6C554} -v
drush ap:update {586328F4-A901-CD54-99E4-82C3B6500000} -v
```
- Run `drush migrate-messages ahjo_decisions:single` to make sure none of the duplicates were skipped yet
- Go to: https://helsinki-paatokset.docker.so/fi/admin/content/decisions
- There …

PP-453: Add scripts for checking decision publication status.

---

conf/cmi/search_api.index.decisions.yml
conf/cmi/search_api.index.policymakers.yml
docker/openshift/crons/base.sh
docker/openshift/crons/search-index.sh

- switching indexation via drush command to be faster and not wait from general cron to run

PLATTA-4694: serach-index with cron

---

public/modules/custom/paatokset_lang_switcher/paatokset_lang_switcher.module
public/themes/custom/hdbt_subtheme/hdbt_subtheme.libraries.yml

This PR adds two missing JS files to the global-scripting library in order to fix tabbed navigation components and decision dropdowns.
**To test**
- Checkout branch, run `make new` 
- Get content to test with:
```
drush mim ahjo_decisionmakers:all
drush mim ahjo_trustees:council
drush ap:update meetings 02900202221 -v
drush ap:update meetings 02900202123 -v
drush ap:update meetings 02900202310 -v
drush ap:update decisions 8c3e5164-930e-4a90-b980-457be86b6792 -v
drush ap:update decisions a2612b7e-331b-cb2c-a118-87758d600004 -v
drush ap:update decisions 3f3c90b5-65c3-480b-b937-5bb91a7c142e -v
drush ap:update decisions 49c80948-6d89-4664-842a-3886e91ab9a2 -v
drush ap:update decisions 6f652461-02e4-40fc-b856-c7267dcfca15 -v
drush ap:update cases hel-2023-001306 -v
drush ap:cdp --queue -v …
```

PP-0: Add missing libraries for tabbed navigation and dropdown components

---

conf/cmi/views.view.decision_makers.yml
docker/openshift/crons/run-aggregated-ahjo-integrations.sh
docker/openshift/crons/run-immediate-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_api/src/AhjoQueueWorkerBase.php
public/modules/custom/paatokset_ahjo_api/src/Commands/AhjoCallbackCommands.php
public/modules/custom/paatokset_ahjo_api/src/Controller/AhjoSubscriberController.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/QueueWorker/AhjoAggregationQueueWorker.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/QueueWorker/AhjoCallbackQueueWorker.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/QueueWorker/AhjoErrorQueueWorker.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/QueueWorker/AhjoOrgChartQueueWorker.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/QueueWorker/AhjoRetryQueueWorker.php
public/modules/custom/paatokset_ahjo_proxy/paatokset_ahjo_proxy.services.yml
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

This PR improves data aggregation, moving decisions and meeting integrations from JSON files into a Drupal queue.
Error and duplication handling is also improved:
* Items that are added to the queue are checked for duplicates, which should reduce changes of the same failed items and large datasets from clogging up the more important queues.
* Cases where data fetching fails are eventually moved to an error queue instead of being retried forever.
**To test**
* Checkout branch, run `make new`
* Login to the container with `make shell` and pull in test data with `drush mim ahjo_decisionmakers:all`
* Read code changes to make sure there's nothing weird there
**Improvements to decisionmakers list**
* Login with `drush uli` and go to https://helsinki-paatokset.docker.so/en/admin/content/decision …

PP-490: Aggregation and queue changes

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

Fixes an issue with old motion URLs getting stuck in the Elasticsearch index when they are converted to decisions. This checks redirect data to load the correct entity instead of showing a blank page.
Also adds some minor improvements to office holder decision list handling.
**Replicate issue**
- Before checking out branch, run these commands:
```
drush mim ahjo_decisionmakers:all --update
drush ap:agg decisions --dataset=all --queue --decisionmaker_id=u4804005010vh1 -v
drush ap:update decisions 11b5b467-e4aa-4a08-904f-c6a38d973ec5 -v
drush ap:update cases hel-2023-009076 -v
drush queue:run ahjo_api_aggregation_queue -v
drush ap:ud -v
drush queue:run ahjo_api_retry_queue -v
```
- Go to: https://helsinki-paatokset.docker.so/fi/asia/hel-2023-009076?paatos=11b5b467-e4aa-4a08-904f-c6a38d973ec5 …

PP-492: Decision fallback from redirect

---

conf/cmi/core.entity_form_display.node.policymaker.default.yml
conf/cmi/core.entity_view_display.node.policymaker.default.yml
conf/cmi/field.field.node.policymaker.field_override_title.yml
conf/cmi/field.storage.node.field_override_title.yml
public/modules/custom/paatokset_ahjo_api/migrations/ahjo_decisionmakers.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module

Fixes issue with overriding decisionmaker titles. Previously the migration wouldn't import titles from the API if they had been changed in Drupal, but this overlooked cases where the title was actually updated in the API.
**To test**
- Run `make drush-cim drush-cr shell`
- Run `drush mim ahjo_decisionmakers:all;drush mim ahjo_decisionmakers:all_sv`
- Open https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto and https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginhallitus
- Edit the finnish and swedish titles to:
- "Helsingin kaupunginvaltuusto" and "Helsingfors stadsfullmäktige"
- "Helsingin kaupunginhallitus" and "Helsingfors stadsstyrelsen"
- When editing the nodes, there should be a new "Override title" toggle below the title. Turn this on for …

PP-491: Improve decisionmaker title field override

---

composer.lock

Updated packages:
```
- Upgrading doctrine/collections (2.1.2 => 2.1.3)
- Upgrading doctrine/reflection (1.2.3 => 1.2.4)
- Upgrading drupal/coder (8.3.20 => 8.3.21)
- Upgrading drupal/helfi_drupal_tools (dev-main 071a7a7 => dev-main 5445ad9)
- Upgrading drupal/json_field (1.2.0 => 1.3.0)
- Upgrading drupal/matomo (1.21.0 => 1.22.0)
- Upgrading drupal/views_bulk_edit (2.8.0 => 2.9.0)
- Upgrading drupal/views_bulk_operations (4.2.4 => 4.2.5)
- Upgrading guzzlehttp/promises (2.0.0 => 2.0.1)
- Upgrading guzzlehttp/psr7 (2.5.0 => 2.6.0)
- Upgrading laminas/laminas-feed (2.20.0 => 2.21.0)
- Upgrading league/csv (9.9.0 => 9.10.0)
- Upgrading masterminds/html5 (2.8.0 => 2.8.1)
- Upgrading nikic/php-parser (v4.16.0 => v4.17.1)
- Upgrading phpdocumentor/type-resolver (1.7.2 => 1.7.3)
- Upgrading …
```

PP-0: Update contrib modules.

---

docker/openshift/crons/run-aggregated-ahjo-integrations.sh

This enables automatic fetching of Swedish trustee translations. Should be merged after a few manual migrations to see that it works without issue.
Or if https://helsinkisolutionoffice.atlassian.net/browse/PP-502 is completed before this is ready to be enabled, this PR should be closed.

PP-501: Enable Swedish trustee translation migration.

---

public/modules/custom/paatokset_datapumppu/drush.services.yml
public/modules/custom/paatokset_datapumppu/src/Commands/DatapumppuCommands.php
public/modules/custom/paatokset_datapumppu/src/Service/Datapumppu.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerLazyBuilder.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

* Add drush command `datapumppu:latest-statements` that fetches trustee statements only from city council memebers
* `git checkout UHF-8581-statements-for-city-council-members`
* Import all trustees (around 400): 
```
drush mim ahjo_trustees:all
```
[UHF-8581]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8581: statements for city council members

---

docker-compose.yml
docker/openshift/crons/run-immediate-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

* Fixes decision content parsing to strip embedded images (and other irrelevant tags). This prevents base64 encoded images from ending up in the ElasticSearch index
* Enable dblog and pull in test data:
```
drush en dblog;
drush ap:agg decisions --dataset=latest --decisionmaker_id=U511053004070VH1 --queue --start=2023-01-01T00:00:00 -v;
drush queue:run ahjo_api_aggregation_queue -v;
```
* Now when you go to https://helsinki-paatokset.docker.so/fi/admin/content/decisions you should get a WSOD or an error page
* Check out the error in the logs, there should be a message about "packets out of order" / "packet size"
* Try to index the decisions you pulled in: `drush sapi-rt decisions;drush sapi-i decisions`
* You should get the same SQL connection errors  
* Try to edit this node: …

UHF-8850: Decision handling improvements

---

docker/openshift/crons/base.sh
docker/openshift/crons/run-datapumppu-integrations.sh

* Add cron job that runs `drush datapumppu:latest-statements -v` every 24 hours.
* `git checkout UHF-8583-datapumppu-cron`
#308 
[UHF-8583]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8583: Add cron job for datapumppu integration

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.services.yml
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/DecisionUrl.php
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/HasTranslation.php

Attempt to index Swedish decision urls correctly. Attempts to clean the code a bit.
* `git checkout UHF-8852-search-language-handling`
* Have a working paatokset database
* City-of-Helsinki/paatokset-search#28
[UHF-8852]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8852 search language handling

---

composer.json
composer.lock

* Updates `paatokset_search` to version [1.0.27](https://github.com/City-of-Helsinki/paatokset-search/releases/tag/1.0.27) with correct assets.
* `git checkout UHF-8852-update-search-app`
* Run `composer install`
[UHF-8852]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8852: update search app

---

conf/cmi/search_api.index.policymakers.yml
docker/openshift/crons/run-aggregated-ahjo-integrations.sh
public/modules/custom/paatokset_ahjo_api/src/Plugin/Deriver/AhjoApiMigrationDeriver.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/ExcludePositionsOfTrust.php

* Import all trustees in a cron job
* Exclude non city council or board members from elastic search index
* `git checkout UHF-8853-fetch-all-trustees`
* `make new shell`
* Install test content `drush en -y paatokset_test_content`
* Import required data (or use existing database):
* Meetings
* `drush ahjo-proxy:aggregate meetings --dataset=latest --queue -v`
* `drush queue:run ahjo_api_aggregation_queue -v`
* Decisionmakers
* `drush migrate-import ahjo_decisionmakers:all`
* `drush migrate-import ahjo_decisionmakers:all_sv`
* **All** Trustees
* `drush migrate-import ahjo_trustees:all`
* ~`drush migrate-import ahjo_trustees:all_sv` (This does not work for me. Maybe requires running `drush ahjo-proxy:get-trustees …

UHF-8853: store all trustees in Drupal

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_api/translations/fi.po
public/modules/custom/paatokset_ahjo_api/translations/sv.po
public/themes/custom/hdbt_subtheme/templates/components/case-attachments.html.twig

Fixes error handling in cases where we get broken attachments for a decision or a motion.
* `git checkout UHF-9027-better-attachment-error-handling`
* If you don't have a Drupal installation yet, run `make new`
* Run `drush locale:update;drush locale:check` 
* Fetch data to test with: 
``` 
drush ap:update decisions c90cf8d5-3984-418f-a216-4bd4ec192fbb -v
drush ap:update cases HEL-2022-011203 -v
drush ap:ud -v
```
* Edit the case: https://helsinki-paatokset.docker.so/fi/asia/hel-2022-011203/c90cf8d5-3984-418f-a216-4bd4ec192fbb
* In the Decision Content section, add three new Attachments with the following data:
* `{"Title": "Oikaisuvaatimus 5.9.2023, saate", "links": [], "PublicityClass": "Julkinen", …

UHF-9027: More visible error handling for broken attachments.

---

public/modules/custom/paatokset_ahjo_api/src/Controller/AhjoSubscriberController.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php

This PR adds a new method for clearing agenda item URLs that is called when a meeting callback is received.
* `git checkout UHF-9026-meeting-agenda-item-cache-fix`
* Run `make drush-cr` (or run `make new` if you don't have your local environment set up yet).
* Make sure you have some decisionmakers available: `drush mim ahjo_decisionmakers:all`
* Pull in a meeting to test with, for example: `drush ap:update meetings 00400202339 -v`
* The meeting has to be an upcoming meeting with a published agenda, but no minutes yet.
* If this meeting has already been updated, find another one from https://paatokset.hel.fi and use its ID instead.
* Then import the motions with `drush ap:gm -v` 
* To actually test if datacaches have been …

UHF-9026: Add new method for clearing agenda item URL caches.

---

composer.json
composer.lock

```
- Upgrading composer/composer (2.2.21 => 2.2.22)
- Upgrading doctrine/collections (2.1.3 => 2.1.4)
- Upgrading doctrine/deprecations (v1.1.1 => 1.1.2)
- Upgrading drupal/helfi_api_base (2.5.5 => 2.5.7)
- Upgrading drupal/helfi_drupal_tools (dev-main 640edf6 => dev-main 8dfd9dd)
- Upgrading drupal/linkit (6.0.0 => 6.0.2)
- Upgrading drupal/pathauto (1.11.0 => 1.12.0)
- Upgrading firebase/php-jwt (v6.8.1 => v6.9.0)
- Upgrading josdejong/jsoneditor (v5.29.1 v5.29.1 => v5.29.1)
- Upgrading justinrainbow/json-schema (5.2.12 => v5.2.13)
- Upgrading laminas/laminas-escaper (2.12.0 => 2.13.0)
- Upgrading phpstan/phpdoc-parser (1.24.1 => 1.24.2)
- Upgrading slevomat/coding-standard (8.13.4 => 8.14.1)
- Upgrading symfony/var-dumper (v5.4.28 => v5.4.29)
- Upgrading drupal/helfi_platform_config …
```

Drupal updates for october, preparations for v3 updates

---

public/modules/custom/paatokset_policymakers/paatokset_policymakers.module
public/modules/custom/paatokset_submenus/src/Plugin/Block/AgendasSubmenuBlock.php

This should only be merged after !294 has been deployed to production and all decision content has been reindexed.

Draft: PP-499: Enable elasticsearch agenda lists

---

public/modules/custom/paatokset_ahjo_api/src/Service/MeetingService.php
public/modules/custom/paatokset_policymakers/paatokset_policymakers.services.yml
public/modules/custom/paatokset_policymakers/src/Controller/PolicymakerController.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

* Prefer currently selected language for meeting PDF files.
This change has a possible issue: Ahjo does not seem to contain minutes of the city council meetings in swedish, only the meeting agenda seems to be translated.
* `git checkout UHF-9024-meetings-files-language`
* `make new shell`
* Install content:
* `drush migrate-import ahjo_decisionmakers:all && drush migrate-import ahjo_decisionmakers:all_sv`
* `drush migrate-import ahjo_meetings:latest`
* [/fi/paattajat/kaupunginvaltuusto/asiakirjat/02900202316](https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginvaltuusto/asiakirjat/02900202316) File should be pöytäkirja in Finnish and Swedish.
* [/sv/beslutsfattare/stadsfullmaktige/dokumenter/02900202316](https://helsinki …

UHF-9024 meetings files language

---

public/.gitignore
public/robots.txt

Less indexed urls for search page.
Added query parameters to robots.txt as disallowed
Cannot be tested on local as far as I know
Cannot be tested on local as far as I know
[rekry](https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/358) & [etusivu](https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/480)
[UHF-8986]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

disallow search query parameters except dm and results

---

composer.json
composer.lock

* Add patch from helfi_proxy that fixes `LANGCODE_NOT_APPLICABLE` urls. Päätökset does not use helfi_proxy module.

Fix tunnistamo redirect_url

---

conf/cmi/openid_connect.client.tunnistamo.yml
public/modules/custom/paatokset_submenus/src/Plugin/Block/PolicymakerSideNav.php

* Removes deprecated openID settings from config
* Fixes an issue with a block constructor that prevented `make new` from running
* Make sure you have Tunnistamo / Helsinki Profiili settings in your env file. (If not, add them an run `make up`)
* `git checkout UHF-0-remove-old-openid-settings`
* `make new` (take a database backup before this so you can return to the previous state)

UHF-0: Remove old openid settings, fix make new

---

composer.json
composer.lock

This PR locks Drupal core to version 10.1.17 and updates the search app.

UHF-0: Lock drupal core version to 10.1.17, update search app

---

conf/cmi/openid_connect.settings.yml

This change fixes profiili login for existing users. The settings was enabled in production as a hotfix.

Set connect_existing_users to true

---

public/sites/default/all.settings.php

Adds automatic AD role mapping for Päätökset project.
Can't be tested locally, just check that the AD groups match the ones in the ticket. Will be tested further on test and staging before production release.
[UHF-9585]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9585: Add AD role mapping for Päätökset

---

public/modules/custom/paatokset_ahjo_api/migrations/ahjo_organization.yml
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php

Fixes issues with organization chart migration and JSON endpoint:
- The migration only saved the first Organization level below ID and not all of them
- JSON endpoint code had a typo which caused a fatal error to be thrown
* Make sure your instance is up and running on correct branch:
* `git checkout UHF-x-org-chart-fixes` 
* `make drush-cr`

UHF-X: Fix errors with org chart import and printing.

---

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php
public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php

Fixes logic error when creating motions. Previously if a meeting had agenda items with the same diary number and title, the system stored all of them in the same node.
This still leaves orphaned motions when the decisions are published.
* Make sure your instance is up and running on `dev` branch
* Run `drush ap:update meetings 00400202414 -v; drush ap:gm -v`
* Go to https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginhallitus/asiakirjat/00400202414
* The points 17 and 18 should have the same URL. 
* `git checkout UHF-9917-motion-creation-fix`
* Run `drush ap:update meetings 00400202414 -v; drush ap:gm -v`
* Reload the page: https://helsinki-paatokset.docker.so/fi/paattajat/kaupunginhallitus/asiakirj …

UHF-9917: Fix logic error when creating motions based on meeting agenda.

---

.github/workflows/test.yml
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Controller/AhjoSubscriberController.php
public/modules/custom/paatokset_ahjo_api/src/Controller/CaseNodeViewController.php
public/modules/custom/paatokset_ahjo_api/src/DisallowedDecisionsListBuilder.php
public/modules/custom/paatokset_ahjo_api/src/DisallowedDecisionsStorageManager.php
public/modules/custom/paatokset_ahjo_api/src/Form/DisallowedDecisionsForm.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/migrate/process/AhjoEntityGenerate.php
public/modules/custom/paatokset_ahjo_api/src/Plugin/migrate/process/SkipDisallowedDecisions.php
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_openid/src/AhjoOpenId.php
public/modules/custom/paatokset_search/src/Commands/DevelopmentDatabaseCleanerCommand.php

* Fixes issue with meeting agenda item language URLs, previously this used the wrong language's URL query parameter.
* Fixes some PHPCS DrupalPractice issues so the checks can be turned back on in Github's CI pipeline
* Fixes simple PHPStan issues.
* Install `dev` branch locally
* You can use `make new` and then `drush en paatokset_test_content` if you don't have the production data to test with
* Import test data:
```
drush mim ahjo_decisionmakers:all --update;
drush mim ahjo_decisionmakers:all_sv --update;
drush ap:update meetings 00400202414 -v;
drush ap:gm -v;
drush ap:ud --logic=case -v;
drush queue:run ahjo_api_retry_queue -v
drush ap:ud --logic=case -v;
```
* Go to https://helsinki-paatokset.docker.so/sv/beslutsfattare/stadsstyrelsen/dokumenter/00400202414
* If you check the agenda …

UHF-9947: Meeting agenda item languge URL fix

---

assets/robots-append.txt
public/robots.txt

Changes robots.txt rule to be more specific in order to prevent it blocking decision URLs.
Use this robots.txt validator: https://technicalseo.com/tools/robots-txt/
%5B%22Henkil%C3%B6st%C3%B6asiat%22%5D&dm=%2202900%22, it should be blocked because of the search queries
*  https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/600
[UHF-9974]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9974: Change robots txt rule to be more specific.

---

conf/cmi/core.entity_form_display.node.trustee.default.yml
conf/cmi/core.entity_view_display.node.trustee.default.yml
conf/cmi/core.entity_view_display.node.trustee.teaser.yml
conf/cmi/field.field.node.trustee.field_policymaker_existing.yml
public/modules/custom/paatokset_search/paatokset_search.deploy.php
public/modules/custom/paatokset_search/paatokset_search.install
public/modules/custom/paatokset_search/src/Plugin/search_api/processor/OrganizationHierarchy.php

Fixes a logic error in decisionmaker search which excluded all trustee nodes from the results.
* `git checkout UHF-10228-fix-policymaker-search`
* `make fresh` (If you use some other commands to import the database dump etc, at least run `make drush-cim drush-updb`.
* If you don't have all trustee nodes locally, run these commands:
```
drush migrate-import ahjo_trustees:all --update;
drush migrate-import ahjo_trustees:all_sv --update
```
* Run `drush sapi-c policymakers;drush sapi-rt policymakers;drush sapi-i policymakers`
* Go to: https://helsinki-paatokset.docker.so/fi/paattajat/
[UHF-10228]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

UHF-10228: Fix trustee node visibility in decisionmaker search.

---

public/themes/custom/hdbt_subtheme/templates/navigation/links--language-block.html.twig

* Use the language object which is set in [helfi_api_base_template_preprocess_default_variables_alter()](https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/173/files#diff-c6358d300a9a1d9956fb89a8182da48065f9342a0f9e4ff310dde94f523a6382R113).
* `git checkout UHF-8909`
* `make new`
* `make shell`
* Enable the test content: `drush en -y paatokset_test_content`
* You can test the existence of `{{ language.id }}`, by dumping the language  `{{ dump(language) }}` in `public/themes/custom/hdbt_subtheme/templates/navigation/links--language-block.html.twig`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1028
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/292
* …

UHF-8909 Language object refactor

---

public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

Changes meeting agenda and minutes list sorting to follow this logic:
1. Sort by sequence number (for agenda lists)
2. Sort by section number (This is the one with §. For minutes, sometimes the order items are handled in changes during the meeting).
Old custom handling for items without sequence numbers has been removed. These are no longer displayed at the end of the list, but are sorted based on their section number.
* `git checkout UHF-10256`
* Make sure you have all decisionmakers imported:
* `drush mim ahjo_decisionmakers:all --update` 
* Get meeting data for testing:
```
drush ap:update meetings U321202411 -v;
drush ap:update meetings U32120249 -v;
drush ap:update meetings U32120241 -v;
drush …
```

UHF-10256: Sort meeting agenda and minutes list correctly

---

conf/cmi/core.extension.yml
conf/cmi/encrypt.profile.real_aes.yml
conf/cmi/encrypt.settings.yml
conf/cmi/key.key.tfa.yml
conf/cmi/tfa.settings.yml
conf/cmi/user.role.admin.yml
conf/cmi/user.role.api_user.yml
conf/cmi/user.role.authenticated.yml
conf/cmi/user.role.content_producer.yml
conf/cmi/user.role.editor.yml
conf/cmi/user.role.elevated_api_user.yml
conf/cmi/user.role.read_only.yml
conf/cmi/user.role.survey_editor.yml

This PR enables the helfi_tfa module and handles custom role configuration.
* `git checkout UHF-10520-enable-tfa`
* Set up the TFA key locally, [instructions here](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/blob/main/modules/helfi_tfa/README.md). Get the TFA encryption key here: https://portal.azure.com/#@helsinginkaupunki.onmicrosoft.com/asset/Microsoft_Azure_KeyVault/Secret/https://hki-fqcslhrd-dev-kv.vault.azure.net/secrets/TFA-ENCRYPTION-KEY
* If you don't have the production or test DB locally, you can follow [these instructions to set up the local environment.](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/PP/pages/6151897290/Lokaali+kehitysymp+rist#Kehitysymp%C3%A4rist%C3%B6n-pystytt%C3%A …

UHF-10520: Enable helfi_tfa module

---

composer.json
patches/big_pipe_status_message_fix.patch
public/themes/custom/hdbt_subtheme/templates/views/views-view-unformatted--latest-articles.html.twig

* Fixed article listing by adding correct class for the listing
* Fixed broken status messages by adding a patch for big pipe which has issues with D10.3 update
* `git checkout UHF-10839 `
* `make fresh`
[UHF-10839]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10839: Fixed latest article listing and added patch for big pipe issue

---

public/sites/default/production.services.yml
public/sites/default/services.yml
public/sites/default/staging.services.yml
public/sites/default/test.services.yml

Fix internal link settings so hel.fi and avustukset.hel.fi show up as external links.
* Create a new landing page or page
* Add a link list component with https://hel.fi, https://www.hel.fi, https://avustukset.hel.fi
* Add a text component with the same links
* These should appear WITHOUT the external link arrow
* `git checkout UHF-x-change-external-link-settings`
* `make drush-cr`

UHF-0000: Fix internal link settings

---

conf/cmi/search_api.index.decisions.yml
conf/cmi/search_api.index.policymakers.yml

Sector fields were added in 6938476a82f46ce6e28648b3d2bd9180bd6fc7b0 along with with `Drupal\paatokset_search\Plugin\search_api\processor\SectorJSON` processor.
This processor was removed in 2f59d7af644ac507a9b8d43eefd4e56c505a2e79, but its config was left in place. This should fix: https://sentry.hel.fi/organizations/city-of-helsinki/issues/39131/
* `git checkout UHF-11094-remove-sector`
* `make fresh`
* Check that search app works after reindexing.
* https://github.com/City-of-Helsinki/helsinki-paatokset/pull/507
[UHF-11094]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11094: remove sector field from index

---

phpstan.neon
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/AgendasSubmenuBlock.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/DocumentsBlock.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/MinutesOfDiscussionBlock.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/PolicymakerMobileNav.php
public/modules/custom/paatokset_submenus/src/Plugin/Block/PolicymakerSideNav.php

* Shown documents are capped at >= 1.8.2018. This PR allows showing documents from 1.1.2017.  
* `git checkout UHF-X-import-old-decisions`
* `make fresh` with production database
* `drush sapi-i meetings`

UHF-X: import old documents

---

composer.json
composer.lock

* Update paatokset_search react app to latest version
* `git checkout UHF-8851`
* `composer update paatokset/paatokset_search`
[UHF-8851]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8851: Update paatokset_search react app to latest version

---

phpstan.neon
public/modules/custom/paatokset_helsinki_kanava/config/schema/paatokset_helsinki_kanava.schema.yml
public/modules/custom/paatokset_helsinki_kanava/paatokset_helsinki_kanava.install
public/modules/custom/paatokset_helsinki_kanava/paatokset_helsinki_kanava.module
public/modules/custom/paatokset_helsinki_kanava/src/Plugin/Block/AnnouncementsBlock.php
public/modules/custom/paatokset_helsinki_kanava/src/Plugin/migrate/source/HelsinkiKanava.php
public/modules/custom/paatokset_helsinki_kanava/tests/src/Kernel/AnnouncementBlockTest.php
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

* Fix helsinki kanava migration
* Enable phpstan for helsinki kanava module
* Fix caching for live stream announcements.
* `git checkout UHF-11285`
* `make fresh`
[UHF-11285]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11285: Fix helsinki kanava

---

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme

* Added alter hooks to use new non-core site branding, navigation etc
* `git checkout UHF-11429`
* `make fresh`
* Update the HDBT theme
* `composer require drupal/hdbt:dev-UHF-11429`
**Test also in a core site just to make sure no styles were broken there**
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1205
[UHF-11429]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11429: Added alter hooks to use non-core navigation, branding and  top header

---

docker/openshift/crons/run-datapumppu-integrations.sh

Sometimes, the API contains mistakes that are fixed by hand by datapumppu team. Without --update flag, changed results in api are not automatically synced to paatokset.hel.fi.
The migration only looks for statements made during the current year, so this should not update the whole database every time the migration is run.

Add --update flag to datapumppu migration

---

public/modules/custom/paatokset_policymakers/src/Controller/PolicymakerNodeViewController.php

* Fix the double canonical link that appears in decisions page
* `git checkout UHF-10949-canonical-url`
* `make fresh`
[UHF-10949]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10949: Add custom logic to handle head links. Remove duplicate canonical URL

---

phpstan.neon
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module

* Fix WSOD on frontpage on test environment. Call to undefined method `getPolicymakerClassById` introduced by #566
Sentry issue:
https://sentry.test.hel.ninja/organizations/city-of-helsinki/issues/22491/?project=213&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0
[UHF-11628]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11628: Fix paatokset_ahjo_api_preprocess_block__frontpage_calendar()

---

phpstan.neon
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_policymakers/paatokset_policymakers.module

- Fix WSOD on policymakers page on test environment. Call to undefined method getDecisionsRoute introduced by #566.
Sentry issue:
https://sentry.test.hel.ninja/organizations/city-of-helsinki/issues/22491/?project=213&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0
- Index decisions
- [policymaker page](https://helsinki-paatokset.docker.so/fi/paattajat/yksikon-paallikko-alueellinen-rakennuttaminen-yksikko) should not crash
[UHF-11628]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11628: Fix paatokset_policymakers_preprocess_node__policymaker()

---

composer.json
composer.lock
public/modules/custom/paatokset_search/paatokset_search.libraries.yml
public/modules/custom/paatokset_search/paatokset_search.services.yml
public/modules/custom/paatokset_search/src/Controller/SearchController.php
public/modules/custom/paatokset_search/src/Plugin/Block/PolicymakerSearchBlock.php
public/modules/custom/paatokset_search/src/SearchManager.php
public/modules/custom/paatokset_search/tests/src/Kernel/Controller/SearchControllerTest.php
public/modules/custom/paatokset_search/tests/src/Kernel/Plugin/Block/PolicymakerSearchBlockTest.php
public/modules/custom/paatokset_search/tests/src/Kernel/SearchManagerTest.php
public/modules/custom/paatokset_search_form/src/Plugin/Block/SearchBlock.php
public/modules/custom/paatokset_search_form/tests/src/Kernel/Plugin/Block/SearchBlockTest.php
public/sites/default/all.settings.php

This PR enables the use of search operators in decision search:
- Updates `paatokset/paatokset_search` to a version that has support for search operators (see https://github.com/City-of-Helsinki/paatokset-search/pull/49)
- Adds support for providing a url for instructions on how to use the operators:
- The node id is provided via an environment variable
- If the node exists and current user has access to view it, a url for current language version is generated and provided for the search root dom-element.
* `git checkout UHF-11527_operators`
* `make fresh`
List of search operator characters: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-quer …

UHF-11527: Enabling search operators

---

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme

* Add Decisions instance name manually to js-variable as a quick fix for the issue of missing instance name.
* `git checkout UHF-11474`
* `make fresh`
[UHF-11474]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11474: Fix accordion memory function in Decisions

---

public/modules/custom/paatokset_ahjo_api/js/meetings_calendar.js
public/modules/custom/paatokset_ahjo_api/src/Service/MeetingService.php
public/modules/custom/paatokset_ahjo_api/translations/fi.po
public/modules/custom/paatokset_ahjo_api/translations/sv.po

* Changed translations in meetings are moved, they should only say meeting is moved and no extra info
* `git checkout UHF-11728`
* `make fresh`
* Link to other PR
[UHF-11728]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11728: Changed translations if meeting is moved

---

public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Plugin/search_api/processor/ColorClass.php
public/modules/custom/paatokset_ahjo_api/tests/src/Kernel/SearchApi/Processor/ColorClassTest.php

This bug was introduced in #566, when some methods from Policymaker service were moved to a Policymaker bundle class. Policymaker::getPolicymakerClass and Policymaker::getPolicymakerClassById had a different default values, so if a decision is missing a policymaker, it should get 'color-sumu'.
https://github.com/City-of-Helsinki/helsinki-paatokset/pull/566/files#diff-5e6c90a5f4f18266e2d99314d0af3738668a4d6a94c45d7fd0296f56e76cc2c3L1980-L1995

UHF-X: Fix default color for decision when policymaker is missing

---

conf/cmi/field.storage.node.field_decision_native_id.yml
conf/cmi/field.storage.node.field_diary_number.yml
conf/cmi/field.storage.node.field_policymaker_id.yml
conf/cmi/field.storage.node.field_unique_id.yml
phpstan.neon
public/modules/custom/paatokset_ahjo_api/config/install/field.field.node.case.field_no_title_for_case.yml
public/modules/custom/paatokset_ahjo_api/config/install/field.field.node.decision.field_decision_case_title.yml
public/modules/custom/paatokset_ahjo_api/config/install/field.storage.node.field_decision_case_title.yml
public/modules/custom/paatokset_ahjo_api/config/install/field.storage.node.field_no_title_for_case.yml
public/modules/custom/paatokset_ahjo_api/includes/paatokset_lang_switcher.php
public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
public/modules/custom/paatokset_ahjo_api/src/Controller/CaseController.php
public/modules/custom/paatokset_ahjo_api/src/Entity/CaseBundle.php
public/modules/custom/paatokset_ahjo_api/src/Entity/Decision.php
public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php
public/modules/custom/paatokset_ahjo_api/tests/src/Kernel/CaseServiceTest.php
public/modules/custom/paatokset_ahjo_api/tests/src/Kernel/Entity/CaseTest.php
public/modules/custom/paatokset_ahjo_api/tests/src/Kernel/Entity/DecisionTest.php
public/modules/custom/paatokset_ahjo_api/translations/fi.po
public/modules/custom/paatokset_ahjo_api/translations/sv.po
public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php

Paatokset makes some heavy DB queries to node fields. This change attempts to optimize this.
This PR should address the following issues:
- https://sentry.hel.fi/organizations/city-of-helsinki/issues/49485/?environment=production&project=177
- https://sentry.hel.fi/organizations/city-of-helsinki/issues/50519/?environment=production&project=177
- https://sentry.hel.fi/organizations/city-of-helsinki/issues/50241/?environment=production&project=177
- https://sentry.hel.fi/organizations/city-of-helsinki/issues/50375/?environment=production&project=177
- https://sentry.hel.fi/organizations/city-of-helsinki/issues/50042/?environment=production&project=177
* `git checkout UHF-11644-create-indexes`
* `make fresh` …

UHF-11644: Create indexes for ID fields

---

public/modules/custom/paatokset_ahjo_api/includes/paatokset_lang_switcher.php

I was testing `main` at staging. My language selector fix from #597 does not work properly.
The issue was caused by me rebasing commits to a different order. The issue should not happen after d2560cc510839030a434d3d6d76d2fd525cdd043, which is merged to `dev`, but #592 is not ready for release yet.
This fixes https://sentry.hel.fi/organizations/city-of-helsinki/issues/44982.

UHF-X: Fix language selector v2

---

public/modules/custom/paatokset_ahjo_api/src/Plugin/migrate/source/AhjoOrganizationSource.php
public/modules/custom/paatokset_ahjo_api/tests/src/Kernel/Entity/OrganizationTest.php

* Organizations should have `existing = 1` if they are published. Previously, the migration set `existing = 1` if they were dissolved. 
* `git checkout UHF-11629-org-charg-component-v2`
* `make new`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/955
[UHF-11629]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11629: Correctly import existing status for organizations

---

public/modules/custom/paatokset_ahjo_api/src/Controller/AhjoApiController.php
public/modules/custom/paatokset_ahjo_api/tests/src/Kernel/Controller/AhjoApiControllerTest.php

* This thing was fixed
* `git checkout UHF-11178`
* `make fresh`
[UHF-11178]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11178: Add policymaker urls to ahjo org chart responses

---

public/themes/custom/hdbt_subtheme/templates/layout/page.html.twig
public/themes/custom/hdbt_subtheme/templates/navigation/links--language-block.html.twig

* Modified templates used in Decisions to enable language toasts on the site as well.
* `git checkout UHF-11697`
* `make fresh`
[UHF-11697]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11697: Enable language toasts on Decisions

---

public/modules/custom/paatokset/paatokset.services.yml
public/modules/custom/paatokset/src/Lupapiste/ItemsStorage.php
public/modules/custom/paatokset/tests/src/Kernel/Lupapiste/ItemsStorageTest.php

* Changed the datetime format to use "O" timezone and set the priority higher than the original datetime service.
* Test the datetime normalizer and the deserialize method.
* `git checkout UHF-11554`
* `make fresh`
* https://helsinki-paatokset.docker.so/fi/kuulutukset-ja-ilmoitukset/rakennusvalvonnan-lupapaatokset
[UHF-11554]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11554 Lupapiste datetime (to dev)

---

public/modules/custom/paatokset_ahjo_api/migrations/ahjo_org_composition.yml

Some organization data was not imported correctly due to changes in the source API that were not detected by the migration. Adding `track_changes: true` ensures that modified entries are re-imported even if they already exist.
[UHF-11554]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11554: Enable change tracking for ahjo_org_composition migration
