README.md
Update documentation with information about Gitflow and Pull request handling.
**To test**
* Read the following sections in README.me and check if they make sense:
* Development best practices
* Coding standards
* Commit messages
* Gitflow workflow
* Pull requests
* Reviewing pull requests
=> PP-81: Documentation about gitflow and PRs.

conf/cmi/core.entity_view_display.tpr_unit.tpr_unit.default.yml, conf/cmi/core.entity_view_display.tpr_unit.tpr_unit.organisation.yml, conf/cmi/core.entity_view_mode.tpr_unit.organisation.yml, conf/cmi/core.extension.yml, conf/cmi/language.content_settings.tpr_errand_service.tpr_errand_service.yml, conf/cmi/language.content_settings.tpr_service.tpr_service.yml, conf/cmi/language.content_settings.tpr_service_channel.tpr_service_channel.yml, conf/cmi/language.content_settings.tpr_unit.tpr_unit.yml, conf/cmi/language/en/core.entity_view_mode.tpr_unit.organisation.yml, conf/cmi/system.action.tpr_unit_update_action.yml, conf/cmi/views.view.tpr_unit_list.yml
****To test
- Run `make drush-cim`
- Check that helfi_tpr -module is enabled
- Check `admin/structure` - TPR entities should be listed there
- Run `drush migrate:import tpr_unit`
- You can view imported units from Content > Integrations > TPR Unit
=> PP-80: TPR Integration

conf/cmi/block.block.helfi_paatokset_footertopnavigation.yml, conf/cmi/block.block.paavalikko.yml
To test:
- `make drush-cim`
- Go to Tools > Menus > **Main menu**, add some placeholder links. Do the same for **Footer - Top navigation** and **Footer - Bottom navigation** menus.
- View the page. Links are now displayed in the header and footer.
=> PP-73: Navigation and footer

azure-pipelines-master.yml, azure-pipelines-pull-request.yml, azure-pipelines-release.yml, azure-pipelines.yml, docker/openshift/Dockerfile, docker/openshift/docker-entrypoint.sh
Docker/openshift and azure-pipelines-\*.yml files  should match the ones in https://github.com/City-of-Helsinki/drupal-helfi except for the repository details being changed for this project.
=> PP-88: YML files for Azure deploy process

.env, .gitignore, README.md, tools/make/Makefile, tools/make/composer.mk, tools/make/drupal.mk, tools/make/include.mk, tools/make/javascript.mk, tools/make/project/install.mk, tools/make/symfony.mk
Updated Druid's `make` scripts  to a newer version.
**To test**
* Before checking out branch, run `make drush-create-dump`
* Checkout branch, run `make down` then `make fresh`
* The operation should complete successfully and your site should be back to the state it was when you exported the database
=> PP-0: Update druid tools.

composer.lock, conf/cmi/language/fi/eu_cookie_compliance.cookie_category.essential.yml, conf/cmi/language/fi/user.mail.yml, conf/cmi/language/ru/user.mail.yml, conf/cmi/language/sv/user.mail.yml, conf/cmi/views.view.scheduler_scheduled_content.yml
**To test:**
* Run `make fresh` (if you have an existing database dump)
* Make sure all modules and Drupal core is actually up-to-date: https://helsinki-paatokset.docker.so/fi/admin/reports/updates
* Test that the site works and nothing weird was introduced in the platform config updates.
**List of updates:**
```
- Upgrading composer/composer (2.1.3 => 2.1.5)
- Upgrading composer/xdebug-handler (2.0.1 => 2.0.2)
- Upgrading doctrine/collections (1.6.7 => 1.6.8)
- Upgrading drupal/core (9.2.0 => 9.2.4)
- Upgrading drupal/core-composer-scaffold (9.2.0 => 9.2.4)
- Upgrading drupal/core-dev (9.2.0 => 9.2.4)
- Upgrading drupal/core-recommended (9.2.0 => 9.2.4)
- Upgrading drupal/easy_breadcrumb (1.15.0 => 2.0.1)
- Upgrading drupal/entity_usage (2.0.0-beta3 => 2.0.0-beta4)
- …
```
=> PP-0: Drupal core and other package updates

composer.lock, conf/cmi/core.extension.yml, conf/cmi/language/fi/views.view.tpr_errand_service_list.yml, conf/cmi/language/fi/views.view.tpr_service_channel_list.yml, conf/cmi/pathauto.pattern.service_entity_pattern.yml, conf/cmi/pathauto.pattern.unit_entity_pattern.yml, conf/cmi/system.action.tpr_errand_service_publish_action.yml, conf/cmi/system.action.tpr_errand_service_unpublish_action.yml, conf/cmi/system.action.tpr_service_channel_publish_action.yml, conf/cmi/system.action.tpr_service_channel_unpublish_action.yml, conf/cmi/views.view.tpr_errand_service_list.yml, conf/cmi/views.view.tpr_service_channel_list.yml, conf/cmi/views.view.tpr_service_list.yml
**To test:**
- Run `make fresh` (if you have an existing database dump)
- Run `make drush-updb` to make sure there aren't any pending database updates
- Make sure all modules and Drupal core is actually up-to-date: https://helsinki-paatokset.docker.so/fi/admin/reports/updates
- Test that the site works and nothing weird was introduced in the platform config updates.
**Updates:**
```
- Upgrading drupal/admin_toolbar (2.4.0 => 2.5.0)
- Upgrading drupal/core (9.2.4 => 9.2.6)
- Upgrading drupal/core-composer-scaffold (9.2.4 => 9.2.6)
- Upgrading drupal/core-dev (9.2.4 => 9.2.6)
- Upgrading drupal/core-recommended (9.2.4 => 9.2.6)
- Upgrading drupal/entity_usage (2.0.0-beta4 => 2.0.0-beta5)
- Upgrading drupal/hdbt (1.3.11 => 1.3.20)
- Upgrading drupal/hdbt_admin (1.3.7 => …
```
=> PP-0: Drupal updates for week 38

public/modules/custom/paatokset_helsinki_kanava/src/Plugin/migrate/source/HelsinkiKanava.php
Converted HelsinkiKanava error throws to Drupal logger warnings.
Testing:
- Run `make new`
- Try running migrations afterwards. Order of migrations should not matter and HelsinkiKanava migration plugin should not throw any errors.
=> PP-188: Fix unnecessary errors

conf/cmi/core.entity_form_display.media.hel_map.default.yml, conf/cmi/core.entity_form_display.media.hel_map.media_library.yml, conf/cmi/core.entity_form_display.paragraph.map.default.yml, conf/cmi/core.entity_form_display.paragraph.remote_video.default.yml, conf/cmi/core.entity_view_display.media.hel_map.default.yml, conf/cmi/core.entity_view_display.media.hel_map.media_library.yml, conf/cmi/core.entity_view_display.paragraph.map.default.yml, conf/cmi/core.entity_view_display.paragraph.remote_video.default.yml, conf/cmi/core.extension.yml, conf/cmi/field.field.media.hel_map.field_media_hel_map.yml, conf/cmi/field.field.node.landing_page.field_content.yml, conf/cmi/field.field.node.page.field_content.yml, conf/cmi/field.field.paragraph.accordion.field_accordion_description.yml, conf/cmi/field.field.paragraph.map.field_map_description.yml, conf/cmi/field.field.paragraph.map.field_map_map.yml, conf/cmi/field.field.paragraph.map.field_map_title.yml, conf/cmi/field.field.paragraph.remote_video.field_remote_video.yml, conf/cmi/field.storage.media.field_media_hel_map.yml, conf/cmi/field.storage.paragraph.field_map_description.yml, conf/cmi/field.storage.paragraph.field_map_map.yml, conf/cmi/field.storage.paragraph.field_map_title.yml, conf/cmi/field.storage.paragraph.field_remote_video.yml, conf/cmi/media.type.hel_map.yml, conf/cmi/paragraphs.paragraphs_type.map.yml, conf/cmi/paragraphs.paragraphs_type.remote_video.yml, conf/cmi/search_api.index.decisions.yml, conf/cmi/user.role.admin.yml, conf/cmi/user.role.content_producer.yml
Ticket: https://helsinkisolutionoffice.atlassian.net/browse/PP-241
Checkout branch and run `drush cim -y; drush cr`
Create new landing page and basic page and test that the new (map and remote video) paragraphs work as well as the old ones.
=> Pp 241 paragraphs for pages

docker/openshift/Dockerfile, docker/openshift/crons/base.sh, docker/openshift/crons/run-callback-queue.sh, docker/openshift/crons/update-translations.sh, docker/openshift/entrypoints/20-deploy.sh, docker/openshift/entrypoints/90-deploy.sh
**To test**
- Read the added shell scripts to make sure they make sense
- Otherwise this can only be tested in the actual environments
=> PP-305: Add cron shell scripts, edit deploy script

composer.json, composer.lock, public/themes/custom/helfi_paatokset/helfi_paatokset.theme
- Test normal pages
- Test policymaker pages
- Test imported news pages
- Test announcement pages
=> PP-362: Navigation fix, lock hdbt to specific version.

public/sites/default/settings.php
Update settings.php with changes from main project template.
=> PP-0: Update settings.php

composer.json, composer.lock
**To test**
- Checkout branch, run `make composer-install` (or `make new`)
- Test the search applications with the same test steps as: https://github.com/City-of-Helsinki/paatokset-search/pull/25
- Decisions search can be tested in https://helsinki-paatokset.docker.so/fi/asia/
- Create landing page with a `/paattajat` URL alias and test the decisionmaker search there
=> PP-455: Update search app

public/modules/custom/paatokset_ahjo_api/src/Service/CaseService.php, public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php, public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
This PR fixes the following issues:
- Latest 2 decisions on office holder page were loaded out of order.
- Office holder decisions list breaks when there are too many decisions or when too many of them have embedded images
**Replicate issues:**
- Before checking out branch, run:
- `make new`
- Import office holder and a lot of decisions:
```
drush ap:update organization u511053004070vh1 -v
drush ap:update decisions {7CED13CB-2D27-C420-BD19-791BC9500005} -v
drush ap:update decisions {06D226B6-0760-4343-BA12-5753C597CBD0} -v
drush ap:update decisions {529C76B7-E5F3-4C5C-9ADD-3B6D01EF1683} -v
drush ap:update decisions {8340D6B4-A691-4014-82F4-79913DA8F724} -v
drush ap:update decisions {52EB54EC-00CB-CCFE-9298-78E327800000} -v
drush ap:update decisions {0A9E7F90-C6FD-C7E4-8431-78E327E00000} …
```
=> PP-474: Office holder decision fixes

composer.json, composer.lock, conf/cmi/filter.format.plain_text.yml
**To test**
- Run `composer install;drush cr;drush updb -y;`
- Click around the site to make sure nothing breaks
- Test that integrations work:
- `drush migrate:import datapumppu_statements -v` 
- `drush migrate-import ahjo_decisionmakers:all -v`
- `drush migrate-import ahjo_trustees:council -v` 
- `drush ap:agg meetings --dataset=latest --queue --start=2023-09-25T00:00:00 --end=2023-10-01T00:00:00 -v`
- `drush ap:agg decisions --dataset=latest --queue --start=2023-09-25T00:00:00 -v`
- `drush queue:run ahjo_api_aggregation_queue -v`
**Updates:**
```
- Upgrading drupal/core (9.5.10 => 9.5.11)
- Upgrading drupal/core-composer-scaffold (9.5.10 => 9.5.11)
- Upgrading drupal/core-dev (9.5.10 => 9.5.11)
- Upgrading drupal/helfi_api_base (2.5.3 => 2.5.5)
- Upgrading …
```
=> UHF-0: Drupal updates.

README.md, azure-pipelines-master.yml, azure-pipelines-pull-request.yml, azure-pipelines.yml
Code and documentation changes to switch main branch to `dev`
=> UHF-0: Change develop to dev branch, update release process.

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/raven.settings.yml, public/modules/custom/paatokset_search/paatokset_search.info.yml, public/modules/custom/paatokset_search/paatokset_search.module, public/modules/custom/paatokset_search/src/Controller/SearchController.php, public/modules/custom/paatokset_search/src/Plugin/Block/PolicymakerSearchBlock.php, public/sites/default/all.settings.php
* Add sentry error monitoring to Drupal
* Add sentry to paatokset-search: https://github.com/City-of-Helsinki/paatokset-search/pull/36
* ~Todo: add new paatokset-search release to composer.json once the PR is reviewed and the new version is released~. 
* Add sentry environment variables
```
SENTRY_DSN="XXXX"
SENTRY_DNS_REACT="YYYY"
SENTRY_ENVIRONMENT="test" # or staging or production
```
Get the sentry DNS from sentry url + `/settings/city-of-helsinki/projects/helfi-paatokset-drupal/keys/`
- https://github.com/City-of-Helsinki/paatokset-search/pull/36
[UHF-9308]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9308: Configure sentry

composer.json, composer.lock, conf/cmi/openid_connect.client.tunnistamo.yml
=> UHF-9458: Upgrade tunnistamo to 3.0

conf/cmi/search_api.index.decisions.yml, conf/cmi/search_api.index.policymakers.yml, public/modules/custom/paatokset_search/src/Plugin/search_api/processor/DecisionmakerSearchfieldData.php
Updated decisionmaker dropdown to include bunch of decisionmakers
Added stuff to index
updated dropdown
* `git checkout UHF-8859`
* `make fresh`
Index and use [updated search](https://github.com/City-of-Helsinki/paatokset-search/pull/39)
[UHF-8859]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-8859: added decisionmakers json to index and created processor

conf/cmi/language/fi/paragraphs.paragraphs_type.custom_content_links.yml, conf/cmi/language/fi/paragraphs.paragraphs_type.meetings_calendar.yml, conf/cmi/language/fi/paragraphs.paragraphs_type.pdf_listing.yml, public/modules/custom/paatokset_ahjo_api/paatokset_ahjo_api.module
❗ Notice! Installing the platform config branch `UHF-8975_paragraph_order` locally will also install the D10.2 version. Make sure to remove the conflict section of your local composer.json file if it still exists. ❗ 
* Updated the order for 'päätökset' related paragraph types.
* Added translations for the custom content links, meetings calendar and pdf listing paragraphs.
* Make sure your instance is up and running on latest dev branch.
* `git pull origin dev`
* `make fresh`
* Checkout this branch  
*  `git fetch -all && git checkout UHF-8975_paragraph_order`
* Update the Helfi Platform config
* `composer require drupal/helfi_platform_config:dev-UHF-8975_paragraph_order -W`
* Run `make drush-cim drush-updb drush-cr`
Check the images below for the correct order:
Landing page
Standard page …
=> UHF-8975 Paragraph order

public/sites/default/all.settings.php
[UHF-9392]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9392: Deployment preflight checks

.github/workflows/artifact.yml, .github/workflows/test.yml, .github/workflows/update-config.yml
[UHF-9617]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9617: Migrate CI to use MySQL 8

conf/cmi/metatag.metatag_defaults.global.yml, conf/cmi/metatag.metatag_defaults.node.yml, conf/cmi/metatag.metatag_defaults.node__trustee.yml, conf/cmi/metatag.metatag_defaults.taxonomy_term.yml
Fix metatag titles to include site name in the middle.
* `git checkout UHF-9692-fix-title-metatag`
* If you don't have production or test database content:
* Run `drush en paatokset_test_content` to create the site structure
* Import some test data with: `drush ap:agg meetings --dataset=latest --queue -v;drush ap:agg decisions --dataset=latest --queue -v;drush queue:run ahjo_api_aggregation_queue -v;drush ap:gm -v;drush mim ahjo_decisionmakers:all;drush mim ahjo_trustees:all`
* Run `make drush-cim drush-cr`
* Check that the HTML title tag follows this structure: "Node title | Site name | City of Helsinki" on various pages and on all three languages:
[UHF-9692]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9692?atlOri …
=> UHF-9692: Fix metatag title definitions.

public/sites/default/all.settings.php
* Preflight check was checking variables that don't exist in this project.
[UHF-9808]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9808: Remove unused variables from preflight check

.github/pull_request_template.md, .github/workflows/artifact.yml, .github/workflows/auto-release-pr.yml, .github/workflows/test.yml, .github/workflows/update-config.yml, compose.yaml, conf/cmi/field.field.node.policymaker.field_dm_organization.yml, conf/cmi/system.action.user_add_role_action.super_administrator.yml, conf/cmi/system.action.user_remove_role_action.super_administrator.yml, conf/cmi/user.role.super_administrator.yml, tools/make/project/install.mk
* Trying to fix [update config](https://github.com/City-of-Helsinki/helsinki-paatokset/actions/runs/8549970164) workflow.
* Ignored php 8.3 for now.
* Ignored phpstan and DrupalPractice `.github/workflows/test.yml` (see [UHF-9912](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9912)).
[UHF-9912]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Run drush helfi:tools:update-platform

.env
* Updates ngingx proxy conf to allow comma separated index values in the URL
* Changes local REACT_APP_ELASTIC_URL environment variable to use nginx proxy instead of the local elasticsearch service.
* `git checkout UHF-10102-change-elastic-proxy-url`
* Make sure you comment out or delete any `REACT_APP_ELASTIC_URL` values in `.env.local` (only leave the one in `.env´).
* `make up` (to make sure the new environment variable updates)
* `make fresh`
* If you have the full prod database, use the database cleaner command: `drush paatokset:decisions:delete -v`, this will make it so you don't have to index all 80 000 decisions.
* Reindex all content: `drush sapi-c;drush sapi-rt;drush sapi-i`
* Check that the …
=> UHF-10102: Update ELASTIC_PROXY_URL variable to point to nginx proxy.

conf/cmi/core.extension.yml
Tested here: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/783
=> UHF-10255: Enable helfi_robots_header module.

conf/cmi/system.action.user_add_role_action.survey_editor.yml, conf/cmi/system.action.user_remove_role_action.survey_editor.yml
* Fix config translations.
[UHF-10424]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10424: Fix config language

README.md
Clean up README.md and add links to documentation in confluence.
[UHF-9661]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9661: First draft of documentation updates.

composer.json, composer.lock, conf/cmi/core.extension.yml
This PR enables helfi_azure_fs module. Should help with filesystem permission issues.
* https://github.com/City-of-Helsinki/drupal-palvelukeskus/pull/60
* https://github.com/City-of-Helsinki/drupal-emergency-site/pull/79
[UHF-10625]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10625: Enable helfi_azure_fs module

docker/openshift/crons/base.sh, docker/openshift/crons/refresh-ahjo-access-token.sh, public/modules/custom/paatokset_ahjo_proxy/src/AhjoProxy.php, public/modules/custom/paatokset_ahjo_proxy/src/Commands/AhjoAggregatorCommands.php
Adds a new method in AhjoProxy and a drush command for checking and refreshing the auth token. Also adds a new cron script to check the token every 15 minutes.
=> UHF-x: Check and refresh AHJO auth token every 15 minutes

composer.json, composer.lock, docker/openshift/crons/refresh-ahjo-access-token.sh, public/modules/custom/paatokset_search/paatokset_search.libraries.yml
* Fixes AHJO access token renewal script which had a broken if block
* Updates search app version with a minor typo fix
[UHF-10959]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10959: Fix access token script, update search app version

conf/cmi/core.entity_form_display.helfi_news_groups.helfi_news_groups.default.yml, conf/cmi/core.entity_form_display.helfi_news_neighbourhoods.helfi_news_neighbourhoods.default.yml, conf/cmi/core.entity_form_display.helfi_news_tags.helfi_news_tags.default.yml, conf/cmi/core.entity_view_display.helfi_news.helfi_news.default.yml, conf/cmi/core.entity_view_display.helfi_news.helfi_news.medium_teaser.yml, conf/cmi/core.entity_view_display.helfi_news_groups.helfi_news_groups.default.yml, conf/cmi/core.entity_view_display.helfi_news_neighbourhoods.helfi_news_neighbourhoods.default.yml, conf/cmi/core.entity_view_display.helfi_news_tags.helfi_news_tags.default.yml
* Added external entity dependencies to prevent config import recursion when creating the site from scratch.
=> UHF-11702 Prevent recursion on site build

conf/cmi/system.site.yml, public/modules/custom/paatokset_policymakers/src/Controller/PolicymakerController.php, public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
Etusivu should be "/" and not "/etusivu"
Prevent whitescreen on proudction, [on testing](https://nginx-paatokset-test.agw.arodevtest.hel.fi/en/decisionmakers/namnden-for-fostran-och-utbildning/documents/U42020205) or [on local](https://helsinki-paatokset.docker.so/en/decisionmakers/namnden-for-fostran-och-utbildning/documents/U42020205)
* `git checkout UHF-X_frontpage`
* `make fresh`
Etusivu works
The endpoint won't cause white screen
=> UHF-X frontpage

public/modules/custom/paatokset_policymakers/src/Controller/PolicymakerController.php
Go to https://helsinki-paatokset.docker.so/en/decisionmakers/kaupunginvaltuusto/discussion-minutes
You should not see white screen
=> prevent whitesceen

public/sites/default/all.settings.php
* https://dev.azure.com/City-of-Helsinki/paatokset/_git/paatokset-pipelines/pullrequest/10730?_a=files
[UHF-10565]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10565: Use Allu credentials from environment variables

composer.lock, conf/cmi/core.entity_form_display.node.landing_page.default.yml, conf/cmi/core.entity_form_display.paragraph.banner.default.yml, conf/cmi/core.entity_form_display.paragraph.list_of_links_item.default.yml, conf/cmi/external_entities.external_entity_type.helfi_announcements.yml, conf/cmi/external_entities.external_entity_type.helfi_hearings.yml, conf/cmi/external_entities.external_entity_type.helfi_surveys.yml, conf/cmi/views.view.er_tpr_unit.yml, conf/cmi/views.view.locked_services.yml, conf/cmi/views.view.locked_units.yml, conf/cmi/views.view.service_list.yml, conf/cmi/views.view.service_units.yml, conf/cmi/views.view.unit_search.yml
- Updated active configuration.
- Updated platform
=> Automatic update

public/modules/custom/paatokset_policymakers/src/Service/PolicymakerService.php
Fix crash on /admin/structure/block.
[UHF-11015]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11015: Fix crash on /admin/structure/block

public/modules/custom/paatokset/README.md
* This thing was fixed
* `git checkout UHF-X-lupapiste-documentation`
* `make fresh`
* Link to other PR
=> Added readme for lupapiste

public/modules/custom/paatokset_ahjo_api/includes/paatokset_lang_switcher.php
See: https://github.com/City-of-Helsinki/helsinki-paatokset/pull/602
=> Fix: https://sentry.hel.fi/organizations/city-of-helsinki/issues/44982

public/modules/custom/paatokset_ahjo_api/config/install/field.field.node.case.field_created.yml, public/modules/custom/paatokset_ahjo_api/config/install/field.storage.node.field_created.yml, public/modules/custom/paatokset_ahjo_api/includes/paatokset_lang_switcher.php, public/modules/custom/paatokset_ahjo_api/tests/src/Kernel/LanguageSwitcherTest.php
* Fix: https://sentry.test.hel.ninja/organizations/city-of-helsinki/issues/18008
* `git checkout UHF-11550-sentry-issues`
* `make fresh`
[UHF-11550]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11550: Fix sentry issue 18008

public/modules/custom/paatokset_ahjo_api/src/Controller/AhjoApiController.php
Ahjo org chart api did not return translations correctly. This fixes that.
* `git checkout UHF-11629-org-charg-component`
* `make fresh`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/955
[UHF-11629]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11629: Fix caching

public/themes/custom/hdbt_subtheme/templates/navigation/links--language-block.html.twig
* Add additional class to identify language-link wrappers by language.
* Check installation instructions from the [hdbt PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/1269).
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1269
* https://github.com/City-of-Helsinki/helsinki-paatokset/pull/623
[UHF-11697]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11697: Fix the nav-toggle functionality when using BigPipe

composer.json, composer.lock, conf/cmi/core.extension.yml
* Enable redis.
* `git checkout UHF-12003`
* `make fresh`
* https://github.com/City-of-Helsinki/drupal-palvelukeskus/pull/153
[UHF-12003]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-12003: Enable redis

public/themes/custom/hdbt_subtheme/templates/block/block--mobile-navigation.html.twig, public/themes/custom/hdbt_subtheme/templates/navigation/links--language-block.html.twig
* Refactor nav-toggle-button template relocation references
* Check testing instructions from the [HDBT PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/1318)
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1318
* https://github.com/City-of-Helsinki/helsinki-paatokset/pull/667
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1794
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/984
* https://github.com/City-of-Helsinki/drupal-emergency-site/pull/162
[UHF-8743]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-8743: hdbt template folder structure refactor

composer.lock
* Updated JSON Field module to latest version
* Make sure your instance is up and running latest version of dev-branch
* `git checkout dev && git pull origin dev`
* `make fresh`
* Switch to feature branch
* `git fetch && git checkout HOTFIX-2025-09-25.1`
* Run code updates
* `composer install`
* `make drush-deploy drush-locale-update drush-cr`
=> UHF-X: Updated JSON Field module to latest version
